/explorerのフィルター部分のstyleを調整
traPtitech/anke-to-UI pull request #157
Opened 2020-12-26 11:25 UTC by annin3

#146 をやりました。
メニューを開いてるときは上向きの矢印に切り替えるようにしました。
![image](https://user-images.githubusercontent.com/63178126/103150521-5d4fd680-47b8-11eb-8a44-58e6fc056a4e.png)
![image](https://user-images.githubusercontent.com/63178126/103150523-68a30200-47b8-11eb-9c60-336947a77ead.png)

2020-12-27 00:09 UTC, ryoha000 requested changes

2020-12-27 00:09 UTC, ryoha000 commented on src/components/Explorer/DropdownContents.vue
> +    padding: 1rem;
ここのクラスに`box-shadow`をつけて`DropdownContent`と下の部分の境界をつけてほしいです。

2020-12-27 00:09 UTC, ryoha000 commented on src/assets/mdi.ts
> +  mdiChevronUp
下と上のアイコンを持ってくるんじゃなくて回転で対応させた方がいろいろ便利なので消しといてください

2020-12-27 00:09 UTC, ryoha000 commented on src/components/Explorer/DropdownMenu.vue
> +          <icon name="chevron-up" :class="$style.icon" />
`isOpen`の値でclassを出し分けましょう
`:class="[$style.icon, isOpen ? $style.rotate : '']"`とかでできます
上の場合は`rotate`というクラスに回転をつけて`icon`っていうクラスにtransitionをつけたらいい感じになります

2020-12-27 00:11 UTC, ryoha000 commented
あと今は出るときにめっちゃパッとでるのでフェードインさせてほしいです

2020-12-27 13:17 UTC, annin3 commented
iconの回転とドロップダウンの枠線は直しました。
フェードインについて以下のリンクのようにやろうとしたのですがうまく行きません。
原因を教えていただきたいです。
https://jp.vuejs.org/v2/guide/transitions.html#%E5%8D%98%E4%B8%80%E8%A6%81%E7%B4%A0-%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88%E3%81%AE%E3%83%88%E3%83%A9%E3%83%B3%E3%82%B8%E3%82%B7%E3%83%A7%E3%83%B3

2020-12-27 14:42 UTC, ryoha000 commented
手元で試してわけじゃないけどコード読んだ感じ`<style module>`のなかに書いてるからだと思う
他のクラスをdev toolで見たらわかるんですが指定したクラス名の後ろにランダムっぽい文字列がある
このランダムな文字列でcssに名前空間を持ち込めてる(詳しくはcss modulesとかを調べてください)
一方`<transition>`コンポーネントでは出るタイミングとかでいろんなクラス名を付け替えてるけどそれには後ろの文字列がつかない
だからスタイルがうまい具合に当たらない
css modules globalとかで調べたら動くようになると思う

2020-12-28 11:46 UTC, annin3 commented
すみません、いろいろ調べたのですがまだうまく行きません。
[ここ](https://qiita.com/mascii/items/1d43f5e5529d3beb433b)の
>transition や transition-group を使いたいときは CSS Modules は使えない?

のところを見るとcss module内でもうまくいきそうなのですが、、、
globalというのいまいち理解できていないのですがそのままだと子コンポーネントまで適用されないみたいな感じでしょうか？

2020-12-30 04:12 UTC, ryoha000 commented
@annin3 
後ろから三番目のコミットでうまくいかない理由
これは上でいったようにcss modulesで自分で指定するクラス名と実際のクラス名は違うからです
ここのstyleのなかで`:global {...}`を使えばうまくいきます

後ろから二番目のコミットでうまくいかない理由
`<transition>`で指定しているのは`enter_active`でcss modulesで指定しているのは`enter-active`だからですね(`-`と`_`)

後ろから一番目のコミットでうまくいかない理由
三番目の逆と二番目の組み合わせです
`:global {...}`のなかで宣言したやつは`$style`から多分触れません

2020-12-30 04:14 UTC, ryoha000 commented on src/components/Explorer/DropdownMenu.vue
> +          :class="[$style.icon, isOpen ? $style.rotate : '']"
`icon`っていうクラスに`transition`をつけてあげたら回転するアニメーションになるのでつけてください

2020-12-30 07:10 UTC, ryoha000 commented on src/components/Explorer/DropdownContents.vue
> +  margin-top: 0.5rem;
これ、ない方が自然じゃない？

2020-12-30 08:05 UTC, annin3 commented
アイコンの回転アニメーションとフェードアウトについてはできましたがフェードインがうまくいきませんでした。

2020-12-30 08:20 UTC, ryoha000 commented on src/components/Explorer/DropdownContents.vue
> +  }
```suggestion
  .fade-enter-from,
  .fade-leave-to {
    opacity: 0;
  }
  .fade-enter-to,
  .fade-leave-from {
    opacity: 1;
  }
```
クラス名の指定ミスですね
ただこのドキュメントのほうが読みやすいのでこっちでお願いします:pray:
https://v3.vuejs.org/guide/transitions-enterleave.html#transitioning-single-elements-components

2020-12-30 08:21 UTC, ryoha000 requested changes

2020-12-30 08:21 UTC, ryoha000 commented on src/components/Explorer/DropdownContents.vue
> +  }
vue 3でtransitionはAPIが変更されたのでその影響ですね

2020-12-30 08:44 UTC, annin3 commented on src/components/Explorer/DropdownContents.vue
> +  margin-top: 0.5rem;
くっついちゃうと変かなと思ったのですが・・・
戻しましょうか？

2020-12-30 08:50 UTC, ryoha000 commented on src/components/Explorer/DropdownContents.vue
> +  margin-top: 0.5rem;
俺は違和感あったんだけど[このへん](https://material-ui.com/components/selects/)みてるとちょっと離れてる方が自然っぽいし今のままで大丈夫
ごめん:pray:

2020-12-30 10:15 UTC, annin3 commented
できました、ありがとうございます！
直したので確認お願いします。

2020-12-30 10:34 UTC, ryoha000 requested changes

2020-12-30 10:34 UTC, ryoha000 commented on src/components/Explorer/DropdownContents.vue
> +    transition: opacity 0.5s ease;
ちょっと遅いからここ0.3sくらいにしてほしい

2020-12-30 10:34 UTC, ryoha000 commented on src/components/Explorer/DropdownContents.vue
> +  <transition name="fade" mode="out-in">
fadeだけだとほかのやつと衝突するかもしれないから`drop-down-content-fade`みたいな感じでお願い
下のクラス名を変えるの忘れずに

2020-12-30 11:56 UTC, ryoha000 approved these changes
よさよさ
:LGTM:

2020-12-30 11:56 UTC, merged