QuestionnaireTableRowの切り分け
traPtitech/anke-to-UI pull request #160
Opened 2020-12-28 06:53 UTC by kohbanye

[#143](https://github.com/traPtitech/anke-to-UI/issues/143)やりました。

2020-12-28 07:51 UTC, ryoha000 requested changes

2020-12-28 07:51 UTC, ryoha000 commented on src/components/Explorer/QuestionnairesTable.vue
> +      headers: ['', '回答期限', '更新日時', '作成日時', '結果'],
headerは変わらないから大文字定数にしてsetupの中から出してほしい(setup内でreturnする必要はある)

2020-12-28 07:51 UTC, ryoha000 commented on src/components/Explorer/QuestionnairesTableRow.vue
> +      type: String,
個々の型、Stringじゃないと思う
`vue`から`PropType`を、`/@/lib/apis`から`Questionnaire`をimportしてサジェストみたいにしたら補完がつく
```suggestion
      type: Object as PropType<Questionnaire>,
```

2020-12-28 07:51 UTC, ryoha000 commented on src/components/Explorer/QuestionnairesTable.vue
> +}
ここは`src/components/Explorer/QuestionnairesTableRow.vue`のほうにつけてほしい(再利用性のため)

2020-12-28 12:39 UTC, kohbanye commented
直しました。

2020-12-30 03:49 UTC, ryoha000 approved these changes
:LGTM:
良さ～～

2020-12-30 03:49 UTC, merged