Explorerで実際のデータを表示させる
traPtitech/anke-to-UI pull request #180
Opened 2021-01-08 10:53 UTC by kohbanye

#144 をやりました

2021-01-08 11:06 UTC, kohbanye commented
https://github.com/traPtitech/anke-to-UI/pull/180/files#diff-eb9798b0763fb31664f34ff3296693aa0d0397084ca87eb2929eaed26197f595R33
↑で`data`を`data.questionnaires`にしたらうまくいったんですけどVeturで
```
Property 'questionnaires' does not exist on type 'QuestionnaireForList[]'.
```
のエラーが出てて直し方が分かりません…

2021-01-08 13:36 UTC, ryoha000 commented
生成したコードが間違ってるんだと思います。
多分swaggerに問題があるのでそれが治されてanke-toリポジトリのほうにマージされたらもう一回`npm run gen-api`してもらう感じになりそうです:pray:

2021-01-08 13:55 UTC, ryoha000 requested changes

2021-01-08 13:55 UTC, ryoha000 commented on src/components/Explorer/use/useOptions.ts
> +    limitDate.getMinutes()
`${limitDate.getFullYear()}/${limitDate.getMonth()}...`みたいな感じで掛けるからそう書いてほしい

2021-01-08 13:55 UTC, ryoha000 commented on src/components/Explorer/use/useOptions.ts
> +    limitDate.getMonth() +
`Date.getMonth()`はなぜか0indexedだから`+ 1`がいる

2021-01-08 13:55 UTC, ryoha000 commented on src/components/Explorer/use/useOptions.ts
> +    limitDate.getMonth() +
桁数はそろえた方がいいと思うから一桁になり得るものは0を付け足すかどうかの処理をする関数を生やした方がいい
このファイル内じゃなくて`/@/lib`以下とかに

2021-01-08 13:55 UTC, ryoha000 commented on src/components/Explorer/use/useOptions.ts
> +  const year = day * 365
```suggestion
  const MINUTE = 60
  const HOUR= MINUTE * 60
  const DAY= HOUR * 24
  const MONTH= DAY * 30.4
  const YEAR= DAT * 365
```

2021-01-08 13:55 UTC, ryoha000 commented on src/components/Explorer/use/useOptions.ts
> +  return Math.round(secondsDifference / year).toString() + '年前'
ほかをelse ifで書いてるならelseで書いてほしい

2021-01-08 13:55 UTC, ryoha000 commented on src/components/Explorer/use/useOptions.ts
> +  if (secondsDifference < minute) {
Math.roundじゃなくて切り捨てのほうがいいと思う

2021-01-09 09:35 UTC, kohbanye commented
直しました

2021-01-09 14:47 UTC, ryoha000 commented on src/lib/util/number.ts
> +  }
ちょっと読みにくいのでこれ使って実装してほしいです:pray:
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

2021-01-10 07:49 UTC, kohbanye commented
直しました

2021-01-10 12:45 UTC, ryoha000 approved these changes
:yosa:
LGTM
本家の方にswaggerの修正が入ったらマージします

2021-01-24 21:03 UTC, ryoha000 commented
本家に修正は入ったからマージします

2021-01-24 21:03 UTC, merged