/explorerの見た目
traPtitech/anke-to-UI pull request #2
Opened 2020-08-30 06:20 UTC by kohbanye

とりあえず見た目を作りました
これであってますか？
よろしくお願いします

2020-08-30 07:02 UTC, ryoha000 commented
iconのこと考えてなかった
すみません:pray:
iconのやつ考えて導入してくれたんだと思うけどSysAd内で統一した方がよさそうだからこっちで入れなおす:pray:
今日中にはいれるからとりあえずcssを直してほしい
具体的には以下のレビューで言います

2020-08-30 07:11 UTC, ryoha000 requested changes

2020-08-30 07:11 UTC, ryoha000 commented on src/components/DropdownMenu.vue
> +      <div v-if="state.isOpenSort" class="dropdown-menu">
```suggestion
      <div v-if="state.isOpenSort" :class="$style.dropdown-menu">
```
っていう風にして`style`タグの中を直してほしい(他の`class`を使っているところも全部)(`style`タグの中については以下のレビューを参照)
参考: https://jp.vuejs.org/v2/guide/class-and-style.html

2020-08-30 07:11 UTC, ryoha000 commented on src/components/DropdownMenu.vue
> +<style lang="scss">
```suggestion
<style lang="scss" module>
```
他の`style`タグのところも同様に
簡単に言うとcssがこのコンポーネントでのみきくようにするやつ
今のままだと他のファイルで同じクラス名が使えない
参考: https://vue-loader-v14.vuejs.org/ja/features/css-modules.html

2020-08-30 07:11 UTC, ryoha000 commented on src/components/QuestionnairesTable.vue
> +table {
タグ名じゃなくて新しくクラスを指定してスタイルを当ててほしい(他も同様)

2020-08-31 04:50 UTC, kohbanye commented
直しました

2020-08-31 06:37 UTC, ryoha000 requested changes
src/static以下も消してください

2020-08-31 06:37 UTC, ryoha000 commented on src/App.vue
> +</style>
masterに追従させてここを消してください

2020-08-31 06:37 UTC, ryoha000 commented on src/components/DropdownMenu.vue
> +          <span class="ti-angle-down" :class="$style.icon"></span>
iconはtraQでいったみたいにしてください:pray:(他も同様)

2020-08-31 06:37 UTC, ryoha000 commented on src/components/DropdownMenu.vue
> +      <button @click="openSort" :class="$style.button">
Files changed見たらわかると思うんですがLintが落ちてるので直してください(他も同様)
そもそも使ってるエディタで警告出なかったら教えてください

2020-08-31 09:29 UTC, kohbanye commented
修正しました

2020-08-31 09:57 UTC, ryoha000 commented
@kohbanye
どうやってmasterに追従させましたか？
コピペして追従させたならこの辺を参考にやり直してみてください
https://kray.jp/blog/git-pull-rebase/

2020-08-31 10:21 UTC, ryoha000 requested changes

2020-08-31 10:21 UTC, ryoha000 commented on src/components/DropdownMenu.vue
> +    icon: Icon
```suggestion
    Icon
```
だけで大丈夫です
上のtemplate内では何も指定しなかったらケバブケースで参照できます(他も同様)

2020-08-31 10:21 UTC, ryoha000 commented on src/components/DropdownMenu.vue
> +<template>
`components`内の作成したファイル群は`Explorer`みたいなフォルダを作ってそっちに移行してください

2020-08-31 10:21 UTC, ryoha000 commented on src/components/DropdownMenu.vue
> +  <div :class="$style.dropdowns">
`dropdowns`じゃなくて`container`とか`wapper`とかの方がいいと思います

2020-08-31 10:21 UTC, ryoha000 commented on src/components/DropdownMenu.vue
> +    </div>
ここはひとつのコンポーネントとして新しいファイルに切り出しましょう(このファイルの名前を`Menus.vue`みたいにして`DropdownMenu.vue`みたいな名前で新しいファイルを作成)
`<dropdown-menu title="並び替え" icon="chevron-down" :options="sortOrders" @open="openSort" />`みたいに使えるコンポーネントにするといいと思います
参考: https://qiita.com/ryo2132/items/f055679e9974dbc3f977#%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88%E9%96%93%E3%81%A7%E3%81%AE%E5%80%A4%E3%81%AE%E5%8F%97%E3%81%91%E6%B8%A1%E3%81%97-props-emit

2020-08-31 10:21 UTC, ryoha000 commented on src/components/DropdownMenu.vue
> +    </div>
上で指摘するようなコンポーネントを作ったらそれに渡すオブジェクトを変えて使いまわしましょう

2020-08-31 10:21 UTC, ryoha000 commented on src/components/DropdownMenu.vue
> +    ]
まず移動後のファイルと同じ階層で`use`という名前のフォルダを作って、`useOptions.ts`みたいなファイルの中にここを切り出してください
切り出したこれらの値を`export`してこのファイルで`import`してください

2020-08-31 10:21 UTC, ryoha000 commented on src/components/QuestionnairesTable.vue
> +  <div>
このくるんでるdivタグは必要ないと思います

2020-08-31 10:21 UTC, ryoha000 commented on src/components/QuestionnairesTable.vue
> +      </tr>
ここを別のファイル(`QuestionnairesTableRow.vue`みたいな名前)に切り出してください

2020-08-31 10:21 UTC, ryoha000 commented on src/pages/Explorer.vue
> +  <div id="app">
このdivタグにはどういう意図がありますか？
idはどんな場合も一意なので基本的につけないでください(特に`app`というidは使用されてて予期せぬバグがおきそう)

2020-09-01 08:36 UTC, kohbanye commented
```
git checkout master
git pull origin master
git checkout explorer
git pull --rebase origin master
```
したのですが何も変わってない気がします。このまま続けても大丈夫ですか？

2020-09-01 15:13 UTC, ryoha000 commented
@kohbanye
ごめんなさい
```
git fetch origin master
git rebase origin master
```
してください
pushするとき`-f`のオプションがいるとおもいます

2020-09-02 11:59 UTC, kohbanye commented on src/pages/Explorer.vue
> +  <div id="app">
何も考えずにつけてました。消しときます。

2020-09-02 12:11 UTC, kohbanye commented
修正しました

2020-09-04 01:35 UTC, ryoha000 requested changes

2020-09-04 01:35 UTC, ryoha000 commented on src/components/Explorer/DropdownMenu.vue
> +  setup(props, { emit }) {
File Changesを見ればわかると思いますがLintの警告が出ているので直してください
使ってるエディタで警告がでない場合は教えてください
`Missing return type on function`だけは無視していいです
あとで警告が出ないようにします

2020-09-04 01:35 UTC, ryoha000 commented on src/components/Explorer/DropdownMenu.vue
> +    }
```suggestion
  setup(props, context) {
    const state = reactive({ isOpen: false })

    const open = (e: any) => {
      context.emit('open', e)
    }
```
`emit`だけをもらうんじゃなくて`context`をもらってそこから`emit`を使ってください

2020-09-04 01:35 UTC, ryoha000 commented on src/components/Explorer/DropdownMenu.vue
> +import { reactive } from 'vue'
```suggestion
import { reactive, PropType } from 'vue'
import { DropdownOption } from './use/useOption'
```
後ろで使うので`PropType`と`DropdownOption`をimportしといてください
`DropdownOption`については後ろで定義

2020-09-04 01:35 UTC, ryoha000 commented on src/components/Explorer/DropdownMenu.vue
> +      type: Array,
```suggestion
      type: Array as PropType<DropdownOption>,
```
とすると補完が利いてうれしいです

2020-09-04 01:35 UTC, ryoha000 commented on src/components/Explorer/DropdownMenu.vue
> +    }
```suggestion
    const open = () => {
      emit('open')
    }
```
`any`型を使うとTSの意味がなくなるので極力使わないでください
`onclick`がcallbackで引数でとれる型は`MouseEvent`ですがそもそも呼び出してるコンポーネントで使っていないのでeventを渡さないでいいです
emitは第二引数以降を呼び出し元にあるcallback関数に引数として渡します

2020-09-04 01:35 UTC, ryoha000 commented on src/components/Explorer/use/useOptions.ts
> +export default {
```
export interface DropdownOption {
  str: string
  opt: string
}
```
みたいに新しいオリジナルの型を定義してそれもexportしてください
型名は微妙な気がするので変えてもらって大丈夫です
これを`sortOrders`の型として使ってください
`targetOptions`についても新しい型を定義して同様にしてください

2020-09-04 01:35 UTC, ryoha000 commented on src/components/Explorer/use/useOptions.ts
> +  sortOrders: [
`export default`の中に入れるんじゃなくて外に出して普通にexportしてください(export方は上の`DropdownOption`と同様)

2020-09-05 08:45 UTC, kohbanye commented on src/components/Explorer/use/useOptions.ts
> +export default {
DropdownMenu.vueのpropsで
```
contents: {
  type: [
    Array as PropType<DropdownSortOrders[]>,
    Array as PropType<DropdownTargetedOptions[]>
  ],
  required: true
},
```
っていう感じであってますか？

2020-09-05 10:07 UTC, ryoha000 commented on src/components/Explorer/use/useOptions.ts
> +export default {
ごめん`[]`書き忘れてた
それで合ってる

2020-09-05 12:12 UTC, kohbanye commented
![err](https://user-images.githubusercontent.com/66658420/92304816-5fe5b080-efbc-11ea-8497-54310c84b0fa.png)
↑のcontentsとsetupのところで`No overload matches this call.`といわれるのですが、どうやって直せばいいですか？調べてもわからなかったので。
あと、使ってるのに`'...' is defined but never used.`と出てくるのは無視してもいいやつですか？

2020-09-05 12:29 UTC, ryoha000 commented
```
setup(props, contaxt) {
  ...
}
```
って感じですね
型がついてうれしいって言うのは主に上の`<template>`部分ですね
あとpropsのtypeはJaveScriptの型である必要があります
as でTypeScriptの型を扱ってる感じです
なのでpropsのtypeのところでやりたいことは多分こんな感じで出来ます
```
type: Array as PropType<Doropdownなんとか[] | Doropdownなんとか[]>
```
unusedはわかんないですが直しても出たらいってください

2020-09-05 14:10 UTC, kohbanye commented
修正しました

2020-09-06 02:15 UTC, ryoha000 requested changes

2020-09-06 02:15 UTC, ryoha000 commented on src/components/Explorer/DropdownMenu.vue
> +export default {
ここみて`defineComponent`にしてください
https://github.com/traPtitech/anke-to-UI/blob/master/src/components/HelloWorld.vue#L16

2020-09-06 02:15 UTC, ryoha000 commented on src/components/Explorer/DropdownMenu.vue
> +import { DropdownSortOrders, DropdownTargetedOptions } from './use/useOptions'
ここのnot usedはこっちが悪かったので修正します:pray:

2020-09-06 03:43 UTC, ryoha000 commented on src/components/Explorer/DropdownMenu.vue
> +import { DropdownSortOrders, DropdownTargetedOptions } from './use/useOptions'
直ったと思うのでマスターに追従させてください

2020-09-08 03:33 UTC, kohbanye commented
修正しました

2020-09-11 15:00 UTC, ryoha000 commented
@kohbanye 
ごめん、頭から抜けてた
後はCSSを読みやすい感じにするだけかなって思ってます
CSS読むのにちょっと時間がかかるので9/12,13 くらいには返せると思います
ホントすみません

2020-09-13 22:56 UTC, ryoha000 requested changes

2020-09-13 22:56 UTC, ryoha000 commented on src/components/Explorer/DropdownMenu.vue
> +  position: relative;
いらない。
`position`の指定は慎重に(=意図をもって)しないとUIが壊れる

2020-09-13 22:56 UTC, ryoha000 commented on src/components/Explorer/DropdownMenu.vue
> +    box-sizing: inherit;
基本inheritだからいらない

2020-09-13 22:56 UTC, ryoha000 commented on src/components/Explorer/Menus.vue
> +    padding-right: 0.5em;
ここはmarginで指定
詳しくはこの前チャンネルに貼ったspaさんのpaddingとmarginの話を参照

2020-09-13 22:56 UTC, ryoha000 commented on src/components/Explorer/DropdownMenu.vue
> +    padding-top: 0.2em;
ここをpaddingで指定するのはきもいので中央ぞろえしたいならこれの親に`align-items: center`つけてください

2020-09-13 22:56 UTC, ryoha000 commented on src/components/Explorer/DropdownMenu.vue
> +    </div>
ここ切り出してください
cssが長いので

2020-09-13 22:57 UTC, ryoha000 commented
@kohbanye
遅くなって本当に申し訳ない:pray:

2020-09-14 03:15 UTC, kohbanye commented
ありがとうございます～
修正しました

2020-09-14 03:17 UTC, ryoha000 approved these changes
LGTM! :LGTM:
お疲れさまでした！
ロジックの実装についてはサーバー待ちって感じですね(一応着手はできます)

2020-09-14 03:17 UTC, merged