Results画面
traPtitech/anke-to-UI pull request #21
Opened 2020-09-06 04:38 UTC by Fogrexon

<template>はほぼ前clientのパクリ
未実装のところはTODOにしてある
型がわからないところはanyになってるので型の仕様がわかったら書き換えます
あとIndividualで呼ばれてるQuestions.vueとPagination.vueはうちの担当かわからなかったのでコメントアウトしてます

2020-09-06 18:13 UTC, ryoha000 requested changes
`Spreadsheet.vue`だけコメントしましたが他のファイルも同じくらいの粒度で分けてください

2020-09-06 18:13 UTC, ryoha000 commented on src/components/Results/Spreadsheet.vue
> +          <span class="ti-clipboard"></span>
iconはtraQでいったみたいにしてください

2020-09-06 18:13 UTC, ryoha000 commented on src/components/Results/Spreadsheet.vue
> +      </div>
ここの部分別のファイルに切り出してください

2020-09-06 18:13 UTC, ryoha000 commented on src/components/Results/Spreadsheet.vue
> +                </span>
ここの部分別ファイルに切り出してください

2020-09-06 18:13 UTC, ryoha000 commented on src/components/Results/Spreadsheet.vue
> +          </tbody>
多分ここcssをがっつりかくので短いですが切り出してください

2020-09-06 18:13 UTC, ryoha000 commented on src/components/Results/Spreadsheet.vue
> +    const responseToString = (body: any): string => {
`import { なんか型 } from '/@/lib/apis'`で型が読めます

2020-09-21 14:34 UTC, Fogrexon commented
ファイルを分けた　JSは途中で分けるのあきらめた

2020-09-25 04:16 UTC, Fogrexon commented
なるほど、ReRequestすればいいのか

2020-09-26 10:41 UTC, ryoha000 requested changes
masterに追従してください

2020-09-26 10:41 UTC, ryoha000 commented on src/components/Results/Individual.vue
> +      type: Object,
```suggestion
      type: Object as PropType<Type>,
```
みたいにすると型が付きます
'vue'からimportできます

2020-09-26 10:41 UTC, ryoha000 commented on src/components/Results/Spreadsheet.vue
> +      </div>
切り出してください

2020-09-26 10:41 UTC, ryoha000 commented on src/components/Results/Spreadsheet.vue
> +  setup(props: Props, context) {
```suggestion
  props: {
    // hogehoge
  }
  setup(props, context) {
```
ってすると型ヒントいらなくなります

2020-09-26 10:41 UTC, ryoha000 commented on src/components/Results/Spreadsheet.vue
> +    const defaultColumns = [
このたぐいの定数は`DEFAULT_COLUMN`みたいにして下さい

2020-09-26 10:41 UTC, ryoha000 commented on src/components/Results/Spreadsheet.vue
> +    const copyTable = (): void => {
ここは別に今しなくてもいいけどasync clipboardっていうのがあります

2020-09-26 10:41 UTC, ryoha000 commented on src/components/Results/Spreadsheet.vue
> +      (): number => defaultColumns.length + props.questions.length
あってもいいけど単純なやつなら型ヒントなくていいと思います

2020-09-26 10:41 UTC, ryoha000 commented on src/components/Results/Spreadsheet.vue
> +        </table>
切り出してください

2020-09-26 10:41 UTC, ryoha000 commented on src/components/Results/Spreadsheet/TableHeader.vue
> +        </span>
ここ切り出してください

2020-09-26 10:41 UTC, ryoha000 commented on src/pages/Results.vue
> +<template>
pageのとこに色々書くならそこはcomponentに切り出してください

2020-10-06 15:15 UTC, ryoha000 requested changes

2020-10-06 15:15 UTC, ryoha000 commented on src/components/Explorer/DropdownContents.vue
> +  <div v-if="isOpen" :class="$style.dropdown_menu">
どっちでもいいんだけど統一したいからclass名は`dropdownMenu`でお願い:pray:(他のところも)

2020-10-06 15:15 UTC, ryoha000 commented on src/components/Explorer/QuestionnairesTableRow.vue
> +    </td>
何回もに分けちゃって申し訳ないけどここも切り出しておいて:pray:

2020-10-13 09:07 UTC, ryoha000 commented
@Fogrexon
どんな感じですか？

2020-10-14 03:31 UTC, Fogrexon commented
@ryoha000 ちまちまと進めてる感じですかね
JSの分割に苦心してます
最小限にしてるつもりではあるけど

2020-10-22 08:56 UTC, ryoha000 commented
たぶんmergeしたと思うんだけど見にくいから
```
git rebase origin/master
(conflict を解消するたび add して git rebase --continue)
git push -f
```
でrebaseしてほしい

2020-10-22 08:56 UTC, ryoha000 commented
コードは明日読みます

2020-10-22 16:26 UTC, Fogrexon commented
これ型があってるかどうかってpushしてlintとかtype checkとかしないと確認できないの

2020-10-22 16:29 UTC, Fogrexon commented
あとnpm run devしてもapis/generatedがないってエラー吐くんだけどテストできるの？

2020-10-22 18:46 UTC, ryoha000 commented
言い忘れてた型のインポートは`npm run gen-aipi`してほしい(traQでもいう)
`npm run type-check`で型の検査ができる
`npm run hoge`のhogeは`package.json`に書いてる

2020-10-23 02:54 UTC, Fogrexon commented
把握しました

2020-10-23 04:49 UTC, Fogrexon commented
`(node:1028) UnhandledPromiseRejectionWarning: Error: Could not find source file in project with the provided file name: api.ts`
って出てくるんだけどどうすりゃいいですか

2020-10-23 05:54 UTC, ryoha000 commented
PCにJava入ってないとダメかも
`npm run gen-api`は正常終了した？

2020-10-23 17:59 UTC, Fogrexon commented
java入れたらできました

2020-10-24 06:20 UTC, Fogrexon commented
individualとかにあるresult以外のとこにあるコンポーネント実装した方がいいんですかね
questionとかinformationとか

2020-10-29 12:21 UTC, ryoha000 commented
@Fogrexon 読んでから返信しようと思ったら忘れてた
実装しなくて大丈夫
しちゃってたら一緒に出してくれていいけど
遅くなってごめん:pray:
draft外してるしもういけるって意味だと解釈してるんだけど、とりあえず上の方でしてるレビュー部分を直しといてほしい

2020-11-04 03:19 UTC, Fogrexon commented
レビュー見てなかった(exlorerと混ざってた)
なんかね、Draftは外れてた(戻し方わからん)
tsファイル書き出し、ロジック実装の時でいいかなと思ってたんですけど今やった方がいいですか(とりあえずdomが崩れなければいいかの気分でいたんだけど)

2020-11-04 07:28 UTC, ryoha000 commented
切り出してないとcss書いた時に長いファイルの上と下を行き来することになるから、切り出すか消すかしてほしい
俺的にこのPRではタグの配置と切り出しをするつもりだった

2020-11-04 09:48 UTC, Fogrexon commented
それは分かってたつもりだけど、ダミーデータ突っ込んで表示されるギリギリのjsを書いたつもりがこうなってしまった
消すつもりだけどcssの編集って画面表示されなくてもどうにかなるもん？

2020-11-05 17:07 UTC, ryoha000 commented
ページに動きをもたらすロジックは書かなくて大丈夫という意味だった
例えばタブの遷移とかソートができなくてもCSSを書く上ではあんまり問題ない。
雑に言うと関数は書かなくてもいいみたいな

2020-12-17 12:24 UTC, Fogrexon commented
tsほぼ消しました

2020-12-23 04:13 UTC, ryoha000 requested changes

2020-12-23 04:13 UTC, ryoha000 commented on src/components/Results/Statistics/Responces.vue
> +<template>
呼び出してる？

2020-12-23 04:13 UTC, ryoha000 commented on src/components/Results/Statistics/Data.vue
> +        <div v-if="isNumberType(question.type)" class="content">
未定義じゃない？

2020-12-23 04:13 UTC, ryoha000 commented
遅くなってごめん
ただ大体読んだからこれからのレビューはそれなりに速いと思う

2020-12-23 05:24 UTC, Fogrexon commented on src/components/Results/ResultTab.vue
> +        <router-link :to="index + ''">{{ tab }}</router-link>
これ確かめんどくさい処理が書いてあって適当にダミーで入れた奴だった気がする

2020-12-23 05:24 UTC, Fogrexon commented on src/components/Results/ResultTab.vue
> +      }
前のanke-toだとクエリパラメータからとってたから今回もそうするんだと思ってます

2020-12-23 05:28 UTC, ryoha000 commented on src/components/Results/ResultTab.vue
> +        <router-link :to="index + ''">{{ tab }}</router-link>
なるほど
じゃあとりあえずここはdivにしといたほうがよさそう

2021-01-06 15:09 UTC, Fogrexon commented on src/components/Results/ResultTab.vue
> +        <router-link :to="index + ''">{{ tab }}</router-link>
spanのほうがいいかと思ってspanにした

2021-01-06 15:15 UTC, Fogrexon commented on src/components/Results/ResultTab.vue
> +  ></component>
v-ifってのは全部列挙するって意味でよろしいんでしょうか
そのつもりで治した

2021-01-06 15:21 UTC, Fogrexon commented on src/components/Results/Spreadsheet/HeaderElem.vue
> +    }
これはおそらく投票結果をソートするときのキーとしてサーバーにリクエスト投げるときに必要になるヘッダーの番号ですね
ロジック書くときに必要になるはずです
分かりやすい名前にしときます

2021-01-06 16:31 UTC, Fogrexon commented on src/components/Results/Statistics/Responces.vue
> +<template>
このコンポーネント自体が呼び出されてるかってこと？
一応Dataから呼ばれてるはず
適当なダミーデータ用意したから目に見えるようになったはず

2021-01-06 16:32 UTC, Fogrexon commented on src/components/Results/Statistics/Data.vue
> +        <div v-if="isNumberType(question.type)" class="content">
未定義でした

2021-01-06 16:40 UTC, Fogrexon commented
直しました

2021-01-08 13:07 UTC, ryoha000 commented on src/components/Results/Spreadsheet/ScrollView.vue
> +    <table v-show="tableForm === 'view'">
特別な理由がないなら`v-show`じゃなくて`v-if`のほうがパフォーマンスがいい

2021-01-08 13:24 UTC, ryoha000 requested changes
上のheader部分に`/results`をいれといてほしい

2021-01-08 13:24 UTC, ryoha000 commented on src/components/Results/ResultTab.vue
> +        <span>{{ tab }}</span>
クリックでcurrentTanComponentを切り替える処理だけ書いてほしい

2021-01-08 13:24 UTC, ryoha000 commented on src/components/Results/ResultTab.vue
> +      <li v-for="(tab, index) in detailTabs" :key="index">
普通に<div>でくるんでその中で<div>にv-forするのでいいと思う

2021-01-08 13:27 UTC, ryoha000 commented
`Individual`、`Statics`、`SpreadSheet`に関してはとりあえずヘッダー部分とコンテント部分を受け取るコンポーネントにまとめてください
v-slotとかで調べたら雰囲気がわかると思います

2021-01-14 06:51 UTC, Fogrexon commented
イメージつかめないんだけどさ、まとめたコンポーネント作ってそこでheaderと内容(Individual,statics,spreadsheet)を表示するってこと？

2021-01-21 19:31 UTC, ryoha000 commented
ごめん完全に返信忘れてた

そう
```
<なんか>
  <template #header>
    <result-header col="[...headerCol]">
  </template>
  <template #content>
    <spreadsheat>
  </template>
</なんか>
```
みたいな

2021-02-08 10:04 UTC, Fogrexon commented
今更だけど上のやつ修正した
いまいちヘッダーとコンテントの分け方が分からないのでこれであってるか確認してください

2021-02-23 20:39 UTC, ryoha000 requested changes
うっかりさんなのでした
ごめんなさい
ページの構造はイメージ通りな感じだった
cssとかについては質問作るところと被ってでかくなるからこのレビューだけやってくれたらマージする
返答遅くてごめん

2021-02-23 20:39 UTC, ryoha000 commented on src/components/Results/ResultTab.vue
> +      async newQuery => {
await してないから async 消して良さそう

2021-02-25 09:48 UTC, Fogrexon commented
package.jsonあたりでコンフリクト起こしてるの怖いんだけどこれmaster側を取り込めばいいですか

2021-02-25 09:49 UTC, Fogrexon commented
なんでresult側が書き換わってるのかわからん

2021-02-28 08:11 UTC, ryoha000 commented
conflict してるのはマージしたからだと思う
こっちでrebaseしたからマージしちゃう

2021-02-28 08:13 UTC, ryoha000 approved these changes

2021-02-28 08:13 UTC, ryoha000 commented
あとはロジック書いてcss書くだけ
LGTM～

2021-02-28 08:13 UTC, merged