Explorerのフィルター部分
traPtitech/anke-to-UI pull request #267
Opened 2021-03-08 14:25 UTC by kohbanye

https://github.com/traPtitech/anke-to-UI/issues/147
クエリパラメータが変更されたときにアンケートを取得するようにしました。
ソートとかの型を付けたんですがつけ方があってるかとどこで型を使うのかが分かりません。

2021-03-09 00:50 UTC, ryoha000 requested changes

2021-03-09 00:50 UTC, ryoha000 commented on src/components/Explorer/use/useOptions.ts
> +export type TargetedOptions = typeof TargetedOptions[keyof typeof TargetedOptions]
```suggestion
export type TargetedOption = typeof TargetedOptions[keyof typeof TargetedOptions]
```

2021-03-09 00:50 UTC, ryoha000 commented on src/components/Explorer/use/useOptions.ts
> +  const sort = (route.query.sort as string | null) ?? '-modified_at'
`sortOrders`内のものかチェックあった方がよさそう

2021-03-09 00:50 UTC, ryoha000 commented on src/components/Explorer/DropdownContents.vue
> +      <router-link
router-linkでやると再描画が見えちゃうから `@click` でgetするようにした方がよさそう

2021-03-09 00:50 UTC, ryoha000 commented on src/components/Explorer/DropdownContents.vue
> +    color: #000000;
親要素に
```
display: flex;
flex-direction: column;
```
つけたほうがわかりやすいからそれで:pray:

2021-03-10 17:06 UTC, kohbanye commented
クエリを設定せずにアンケートをgetするようにしたんですけど、クエリはあったほうがいいですか？

2021-03-18 22:52 UTC, ryoha000 requested changes
めっちゃ遅くてホント申し訳ないです:pray::gomen:

2021-03-18 22:52 UTC, ryoha000 commented on src/components/Explorer/use/useOptions.ts
> +  opt: TargetedOption
`${boolean}`
みたいにかける

2021-03-18 22:52 UTC, ryoha000 commented on src/pages/Explorer.vue
> +    const getQuestionnairesForOption = (
これわざわざ.vueファイルにもってきてるけどどういう意図がありますか？
ロジックはtsに置いといたほうが読みやすい気がします

2021-03-18 22:52 UTC, ryoha000 commented on src/pages/Explorer.vue
> +    const getQuestionnairesForOption = (
そもそもこの関数でやることは`dropdown-menu`でやった方がいい気がする(v-model使うって言ったところを参照)

2021-03-18 22:52 UTC, ryoha000 commented on src/pages/Explorer.vue
> +    const option = {
refにくるんで`v-model`で`dropdown-menu`に渡した方が嬉しそう
受け取る側(`dropdown-menu`)はこれと同じふうにしたらできる
https://github.com/traPtitech/booQ-UI/blob/master/src/components/UI/SearchInput.vue

2021-03-18 22:52 UTC, ryoha000 commented on src/pages/Explorer.vue
> +    const option = {
optionを`dropdown-menu`が返すという意味です

2021-03-18 22:52 UTC, ryoha000 commented on src/components/Explorer/DropdownMenu.vue
> +    const close = (newOption: SortOrder | TargetedOption) => {
emitsのところで型を宣言できるので忘れてたんですがお願いします:pray:
```
emits: {
    close: () => true
  },
```
みたいな感じ
`open`もお願いします
trueを返してるのはvoidだとエラーになっちゃうからです

2021-03-18 22:52 UTC, ryoha000 commented on src/components/Explorer/DropdownMenu.vue
> +    const close = (newOption: SortOrder | TargetedOption) => {
他のemitsもお願いします(Explorer以下だけ):pray:

2021-03-26 06:36 UTC, kohbanye commented on src/pages/Explorer.vue
> +    const getQuestionnairesForOption = (
意図なかったので変えときます

2021-03-26 06:52 UTC, kohbanye commented
`v-model`使うようにしました。
`option`は変更できてる気がするんですが`watch`しててもアンケートが取得されません。どこかまちがってますか？

2021-03-27 21:01 UTC, ryoha000 requested changes
ちょっと今更だけど見やすくなると思うのでお願いします:pray:

2021-03-27 21:01 UTC, ryoha000 commented on src/components/Explorer/DropdownMenu.vue
>      }
このchangeをただemitするだけにしてMenuでoptionをつくるみたいなの

2021-03-27 21:31 UTC, ryoha000 commented
バグの原因は`Menus`で
```
const option = ref(props.modelValue)
```
やっててExplorerに変更が伝わってないからだった(その時点での値をコピーしてるだけ)
でも↑のレビューでいったみたいにデータの受け渡しのフロー大きく変えてほしいから問題ないと思う

2021-03-27 21:33 UTC, ryoha000 commented
レビュー言葉足らずな気がするんで方針？？？ってなったら聞いてください＞＜

2021-04-02 18:13 UTC, kohbanye commented
直しましたー

2021-04-02 19:28 UTC, ryoha000 commented
言ったところはいい感じです:yosa:
言葉足らずでした
背景としてこの`DropdownMenu`をいろんなところで使えるものにしたいというのがありました
今のところoption関連しか使えない状態なので汎用的な感じにしてほしいです
後ろに書くレビューで補足します

2021-04-02 19:35 UTC, ryoha000 requested changes

2021-04-02 19:35 UTC, ryoha000 commented on src/components/Explorer/Menus.vue
> +      nontargeted: false
ここどうせstringにキャストするし`"false"`みたいにしていいと思う
`DropdownMenu`のロジックも見やすくなるし

2021-04-02 19:35 UTC, ryoha000 commented on src/components/Explorer/DropdownContents.vue
>        type: Array as PropType<DropdownSortOrders[] | DropdownTargetedOptions[]>,
```suggestion
      type: Array as PropType<String[]>,
```
にしてoptについてはMenusの中で対応関係を作ると汎用的なコンポーネントになると重ます

2021-04-07 07:06 UTC, kohbanye commented
直しました

2021-04-10 01:34 UTC, ryoha000 commented on src/components/Explorer/use/useOptions.ts
> +export const stringToOption = (str: string): string => {
この関数は
```
export const stringToOption = <T>(str: string, map: Map<string, T>): T => {
  const option = map.get(str)
  if (!option) {
    throw 'invalid key'
  }
  return option
}
```
みたいにして上の`sortOrders`を
```
export const sortOrderMap: [string, SortOrder][] = [
  ['最近更新された', '-modified_at'],
  ['最近更新されていない', 'modified_at'],
  ['タイトル順', 'title'],
  ['タイトル逆順', '-title'],
  ['最新', '-created_at'],
  ['最も古い', 'created_at']
]
```
みたいな感じにして`Menus`内で
- sortOrderを作る
- `stringToOption(optionStr.value.sort, new Map(sortOrderMap))` みたいな感じで `stringToOption` に渡す
をしてあげるとうまい具合になるとおもう

2021-04-10 01:34 UTC, ryoha000 commented on src/components/Explorer/use/useOptions.ts
>  }
```suggestion
export interface Option {
  sort: SortOrder
  page: number
  nontargeted: TargetedOption
}
```

2021-04-10 01:34 UTC, ryoha000 commented on src/components/Explorer/use/useOptions.ts
> +export type TargetedOption = `${boolean}`
```suggestion
type TargetedOption = `${boolean}`
```

2021-04-10 01:34 UTC, ryoha000 commented on src/components/Explorer/use/useOptions.ts
> +export type SortOrder = typeof SortOrders[keyof typeof SortOrders]
```suggestion
type SortOrder = typeof SortOrders[keyof typeof SortOrders]
```

2021-04-15 08:16 UTC, kohbanye commented
直しました

2021-04-15 13:08 UTC, ryoha000 approved these changes
:yosa:
LGTM!

2021-04-15 13:08 UTC, merged