targetedの大枠を作りました
traPtitech/anke-to-UI pull request #30
Opened 2020-09-17 04:16 UTC by annin3

いろいろおかしいところあると思うので確認していただければと思います。

2020-09-17 07:42 UTC, ryoha000 requested changes
全体的にいい感じです
masterにあわせといてください
cssについては別のPRで

2020-09-17 07:42 UTC, ryoha000 commented on src/components/Targeted/Card.vue
> +    :class="$style.body"
`body`はhtmlの要素名みたいで違和感あるから`container`とかにしてほしい

2020-09-17 07:42 UTC, ryoha000 commented on src/components/Targeted/Card.vue
> +    <div :class="$style.table_item_title">
`tableItemTitle`みたいな形にしてほしいです
命名規則的にはどっちでもいいんですが一応そっちで統一したいので(他も同様)

2020-09-17 07:42 UTC, ryoha000 commented on src/pages/Targeted.vue
> +  <div class="wrapper">
このdivタグいらなそう

2020-09-17 07:42 UTC, ryoha000 commented on src/components/Targeted/Card.vue
> +        <th class="content column res-time-limit">
ここのclass指定いらないと思います
もともとのやつでついてたのはcssフレームワークを使ってたからですね

2020-09-17 07:42 UTC, ryoha000 commented on src/components/Targeted/Card.vue
> +        <th class="content column modified-at">
ここもclass指定いらないと思います

2020-09-19 06:58 UTC, annin3 commented
もろもろ直しました

2020-09-19 08:39 UTC, ryoha000 commented
@annin3 いいと思う
rebaseして最新のmasterに合わせてくれたらマージしちゃいます
cssとかに関してはもう少し現anke-toに近づけてくれたら(わかんなかったら聞いてください)PR出してもらってなんか言う感じで
Card.vueはもうちょっと分割しそうだけどとりあえずはこのままで(別に適当に分割してくれてもいいです)

2020-09-19 14:28 UTC, annin3 commented
rebaseよくわからず調べながらやったのですが、これってできてますか？

2020-09-20 14:28 UTC, ryoha000 approved these changes
LGTM

2020-09-20 14:29 UTC, merged

2020-09-25 05:13 UTC, HoiDam commented
草草草草草草草草草草草草草草草