サイドバー、レスポンシブ対応
traPtitech/anke-to-UI pull request #319
Opened 2021-04-24 15:42 UTC by annin3

#149 です
- ページ幅でハンバーガーとサイドバーの表示切り替えをできるようにしました。
以下で詰まってます
- サイドバーを非表示にしたときにメインのコンテンツが左に寄らない
- クリックでのアイコンの切り替えが上手く行かない
- クリックでのメニューの表示切り替えの実装の方針が立てられない

よろしくお願いします

2021-04-26 08:08 UTC, ryoha000 commented
> サイドバーを非表示にしたときにメインのコンテンツが左に寄らない

これは`App.vue`の`style`内で`grid`の指定をしててそれを変えてないからですね
ここは僕が書いたんですけど変え辛いので`flex`で書き直しちゃってください:pray:

> クリックでのアイコンの切り替えが上手く行かない

下のレビューで

> クリックでのメニューの表示切り替えの実装の方針が立てられない

全体の方針と関係するので下のコメントで

2021-04-26 08:18 UTC, ryoha000 commented
全体の実装方針は`isMobile`という変数の状態を見てレイアウトを変えるようにする、というものです
実装自体は↓のコミットと大体同じようになります
https://github.com/traPtitech/booQ-UI/pull/501/commits/89ebcca0de085860b3d07db8529f3335750b9751
`display: none;`で表示非表示を変えるより`v-if`のほうがjsから簡単に触れてうれしいです

コードの説明をしようと思ったんですがどの辺が分からないかわからなかったので疑問に感じたところを聞いてくれたらと思います:pray:

2021-04-26 08:25 UTC, ryoha000 requested changes

2021-04-26 08:25 UTC, ryoha000 commented on src/components/Navigation/Header.vue
> +    }
切り替えがうまくいかないのは`isOpen`や`emits`の`open`がこのコンポーネントに渡されてないからですね
渡し方については[ここ](https://github.com/traPtitech/anke-to-UI/blob/master/src/components/Explorer/Menus.vue)みたいに変数は`:{{ 変数名 }}="変数"`、`emit`のやつは`@{{ イベント名 }}="関数"`で渡せます
ドキュメントはこことか
https://v3.ja.vuejs.org/guide/component-props.html#%E9%9D%99%E7%9A%84%E3%81%82%E3%82%8B%E3%81%84%E3%81%AF%E5%8B%95%E7%9A%84%E3%81%AA%E3%83%95%E3%82%9A%E3%83%AD%E3%83%8F%E3%82%9A%E3%83%86%E3%82%A3%E3%81%AE%E5%8F%97%E3%81%91%E6%B8%A1%E3%81%97
https://v3.ja.vuejs.org/guide/component-custom-events.html#%E3%82%A4%E3%83%98%E3%82%99%E3%83%B3%E3%83%88%E5%90%8D

2021-04-29 19:54 UTC, ryoha000 commented
@annin3 
どんなかんじですか？
雑な自覚があるので意図とかガンガン聞いてください

2021-04-30 00:37 UTC, annin3 commented
@ryoha000 すみません、ちょっとまだ手を付けられてないです。。。
今日or明日見れると思うのでその時またお願いします:pray:

2021-05-04 12:50 UTC, ryoha000 requested changes

2021-05-04 12:50 UTC, ryoha000 commented on src/App.vue
> +}
使ってないなら消しちゃってください

2021-05-04 12:50 UTC, ryoha000 commented on src/App.vue
> +    }
openでつつまなくてもtoggleSideBarShownを返せばいいとおもう(というか現状ではつかってないけどこのsetup内で返してる)

2021-05-04 12:50 UTC, ryoha000 commented on src/App.vue
> +  display: flex;
ここに`flex: 1;`を追加して`desktopSideBar`の`height`の指定を消したら下切れるやつがなくなります
![image](https://user-images.githubusercontent.com/48485650/117002591-b60f1d00-ad1e-11eb-9e38-99366a333d06.png)

2021-05-04 12:50 UTC, ryoha000 commented on src/App.vue
> +      :can-side-bar-shown="canSideBarShown"
新しいclassを当てて`flex-shrink: 0;`を指定してください(縮んで欲しくないので)
伸びてほしくもないですが`flex-grow`の初期値は0なので指定する必要はないです
https://developer.mozilla.org/ja/docs/Web/CSS/flex-grow

2021-05-04 12:50 UTC, ryoha000 commented on src/use/isMobile.ts
> +const MOBILE_BREAKPOINT = '1024'
ちょっとでかすぎな気がする
スマホサイズ基準にして良さそう

2021-05-04 12:50 UTC, ryoha000 commented on src/components/Navigation/SideBar.vue
> +  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.26);
影はなんかサイドバーとヘッダーで高さの差があるみたいで微妙な気がする
高さの差をつけるならヘッダーが上の方がいいと思うけどそれもなんかびみょい

![image](https://user-images.githubusercontent.com/48485650/117004700-51a18d00-ad21-11eb-8aef-e8ea803667de.png)

同じ階層みたいに見せるなら`box-shadow: 4px 0 3px -2px rgba(0, 0, 0, 0.26);`とかでそれっぽくなったけどどうだろ？

全体的にマテリアルデザインっぽくなってると思ったから調べてみたけど影ない方が主流っぽい？

俺の適当デザイン観だからあてにならんかも

2021-05-04 12:50 UTC, ryoha000 commented on src/components/Navigation/Header.vue
> +    open: () => true
イベント名はtoggleの方が明確でいいと思う

2021-05-04 12:50 UTC, ryoha000 commented on src/components/Navigation/Header.vue
> +    </div>
divでくるんでるせいでハンバーガーメニューが中央ぞろえにならないから外に出してv-ifとv-else-ifの方がいいと思う

2021-05-09 15:40 UTC, annin3 commented
@ryoha000 
ヘッダー&サイドバー周りのstyle調整しました
issueの内容はキリついたかなと思いますがいかがでしょうか

2021-05-10 01:10 UTC, ryoha000 requested changes
テーブル部分で横スクロールできて破壊されるけどそれはまた別のissueで
やった修正はresolve conversationでとじてください

2021-05-10 01:10 UTC, ryoha000 commented on src/App.vue
> +      <side-bar v-if="!canSideBarShown" :class="$style.desktopSideBar" />
外側をクリックしたときも閉じてほしい
どんな方法でやってくれてもいいけどbooQではこうしてて見やすいねってなった
https://github.com/traPtitech/booQ-UI/pull/501/commits/36a4332807c289f16d47c0786073c47b723f740c

2021-05-10 01:25 UTC, annin3 commented
あ～ごめんなさい、6日前のコメント見逃してました。。。。:pray:
直します

2021-05-20 10:00 UTC, annin3 commented on src/App.vue
> +      <side-bar v-if="!canSideBarShown" :class="$style.desktopSideBar" />
他のページに飛んだときに閉じるようにはできましたが外側クリックで閉じるのはbooQのどこのコードでやってるのかわかりませんでした。。。

2021-05-20 10:04 UTC, annin3 commented on src/components/Navigation/SideBar.vue
> +  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.26);
desktopでは平らになるようにしました。
mobile版はヘッダーの下にsidebarを表示させてさらにその下にoverlayをかけるようにしました。
- 違和感はなくなったと思うのですがどうでしょうか？
- overlayかけるときにフェードインのアニメーションをつけたいのですがうまくいきません。どこがだめでしょうか。

2021-05-20 10:08 UTC, annin3 commented on src/App.vue
> +      :can-side-bar-shown="canSideBarShown"
すみません、縮んでいるというのがどこを指しているのかわかりませんでした。
とりあえずheader-componentにclass当てましたがどこも変化なさそう・・・

2021-05-21 09:28 UTC, ryoha000 commented on src/App.vue
> +      :can-side-bar-shown="canSideBarShown"
何かを思ってつけてっていったんですが何だったか忘れちゃいました
まぁつけてて損はないと思うのでこれで:pray:

2021-05-21 09:54 UTC, ryoha000 commented on src/App.vue
> +      <side-bar v-if="!canSideBarShown" :class="$style.desktopSideBar" />
ちょっと張ったページが悪かったですね
↓でやってます
https://github.com/traPtitech/booQ-UI/blob/master/src/components/Navigation/Navigation.vue#L10-L15
booQは[ここ](https://booq-dev.trapti.tech/)で環境が立ってるので`Navigation`部分とここの`z-index`をdev toolでいじってみるとわかるかもです
同じ`z-index`でも動いてるのはVueのtemplateの読み込み順序の問題だと僕は思ってます

2021-05-21 10:04 UTC, ryoha000 commented on src/App.vue
> +  }
`transiton`自体は`overlay`につけちゃっていいと思う

2021-05-21 10:13 UTC, ryoha000 commented on src/components/Navigation/SideBar.vue
> +  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.26);
> 違和感はなくなったと思うのですがどうでしょうか？

なんかよくよく考えたらほかの部分も高さの差あるしいい気がしてきたから:yosa:です

> overlayかけるときにフェードインのアニメーション

overlayのフェードインは多分`transtion`が入れ子になってるのが悪そう？あんまちゃんと調べてない
https://github.com/traPtitech/anke-to-UI/pull/319/files#diff-7a7a37b12ee1265d7e27577ec286120d2cbc0940908635e264a2be44ccb9a8a0R10-R18

2021-05-21 10:16 UTC, ryoha000 commented on src/App.vue
> +      </transition>
ここ長いから切り出してほしい

2021-05-21 13:47 UTC, ryoha000 commented on src/App.vue
> +  height: 100vh;
100vhだとスクロールできちゃうので変えてほしいです

2021-05-26 10:36 UTC, annin3 commented on src/App.vue
> +  height: 100vh;
以下で詰まってます

- モバイルレイアウトで下まで伸びてくれない
- router-viewの高さまでしか伸びてくれない

どうすればよいでしょうか。。。
![image](https://user-images.githubusercontent.com/63178126/119646039-a8e6d900-be59-11eb-84a4-a9c2c2b5e721.png)

![image](https://user-images.githubusercontent.com/63178126/119645998-9b315380-be59-11eb-829c-cc0df821828b.png)

2021-05-26 13:08 UTC, ryoha000 commented on src/App.vue
> +  display: flex;
`flex: 1;`でいけます

2021-05-26 13:11 UTC, ryoha000 commented on src/components/Navigation/SideBarWrapper.vue
> +      ></div>
```suggestion
      />
```

2021-05-26 13:11 UTC, ryoha000 commented on src/components/Navigation/SideBarWrapper.vue
> +        @click="toggleSideBarShown"
未定義ですよ(wipなだけ？)

2021-05-26 17:19 UTC, annin3 commented on src/App.vue
> +  display: flex;
いけませんでした・・・
flex: 1で横方向にいい感じにしてくれるって感じだと思ってたんですが間違ってますかね？
あとモバイルに`  height: 100%;`が効かないのはどうしてでしょうか

2021-05-26 18:03 UTC, ryoha000 commented on src/App.vue
> +  display: flex;
flexが横方向にいい感じになるのは`flex-direction`が`row`になってるからですね(初期値で)
この要素についてる`flex-direction`は`column`なので縦方向にいい感じになります

`height`云々は多分`min-height`にすれば解決します

2021-05-26 18:07 UTC, ryoha000 commented on src/App.vue
> +  display: flex;
あ～というかスクロールはコンテンツ部分だけでするのが正解だと思います
眠くて頭が回らないので詳しい話は起きたらします

2021-05-27 07:46 UTC, ryoha000 commented
動く`git diff`貼っておきます
なかなか言語化しづらいんですが`position: absolute;`とか`box-sizing: border-box;`とか`overflow`とか`height(width)`の`%`はどこ基準なのかとかを調べてみたらいいと思います
調べてみてなんでこれで動くのかわかんなかったら聞いてください
```
PS E:\workspace\anke-to-UI> git diff
diff --git a/src/App.vue b/src/App.vue
index 7180c58..41a26fa 100644
--- a/src/App.vue
+++ b/src/App.vue
@@ -72,15 +72,18 @@ export default defineComponent({
 .container {
   display: flex;
   flex-direction: column;
+  height: 100%;^M
 }
 .header {
   flex-shrink: 0;
 }
 .content {
   padding: 1.5rem;
+  overflow-y: auto;^M
 }
 .main {
   display: flex;
   flex: 1;
+  min-height: 0;^M
 }
 </style>
diff --git a/src/index.scss b/src/index.scss
index 15cd680..9c01584 100644
--- a/src/index.scss
+++ b/src/index.scss
@@ -6,6 +6,7 @@ body {
   width: 100%;
   margin: 0;
   padding: 0;
+  box-sizing: border-box;
 }

 #app {
@@ -15,6 +16,7 @@ body {
   text-align: center;
   height: 100%;
   width: 100%;
+  box-sizing: border-box;
 }

 ul {
@@ -22,3 +24,9 @@ ul {
   margin: 0;
   list-style: none;
 }
+
+*,
+*:before,
+*:after {
+  box-sizing: border-box;
+}
```

2021-05-27 15:05 UTC, annin3 commented
理解できました、ありがとうございます
修正したのでよろしくお願いします

2021-05-27 18:25 UTC, ryoha000 commented
@annin3 lint落ちてるので直しといてください:pray:

2021-05-27 18:30 UTC, ryoha000 reviewed
見た感じよさそうです！！！
ただ眠くてあんまり頭が回ってないので明日またみて良さそうだったらマージします:+1:

2021-05-27 18:30 UTC, ryoha000 commented on src/index.scss
> +}
改行

2021-05-28 19:04 UTC, ryoha000 approved these changes
:yosa:LGTM:yosa:

2021-05-28 19:04 UTC, merged