Explorerの検索部分
traPtitech/anke-to-UI pull request #337
Opened 2021-05-07 07:43 UTC by kohbanye

https://github.com/traPtitech/anke-to-UI/issues/148
コンポーネント切り出して、検索できるようにしました。

2021-05-07 15:39 UTC, ryoha000 requested changes
めっちゃいい感じだと思う
アイコンの大きさが違うのだけ気になるからそこだけお願いします:pray:
![image](https://user-images.githubusercontent.com/48485650/117474329-caa91a80-af95-11eb-9c78-e8324938a9a9.png)

2021-05-10 09:52 UTC, kohbanye commented
なおしました

2021-05-11 01:00 UTC, ryoha000 commented
見た目のサイズが違うだけで同じサイズでしたね(何も見てなかった)
もうちょい大きい方がいいかなと思ってホントにちょっとした変更だったので僕がpushしちゃいました :pray:

2021-05-11 01:00 UTC, ryoha000 approved these changes
:yosa::LGTM:

2021-05-11 01:00 UTC, merged