リザルトのデータ受け渡しto
traPtitech/anke-to-UI pull request #339
Opened 2021-05-09 14:02 UTC by Fogrexon

一旦こんな感じでどうですか

2021-05-16 03:55 UTC, Fogrexon commented
route.params.idがNaNだった時の処理って今は書かない？

2021-05-16 04:14 UTC, ryoha000 commented
いや書いてほしい(というか書いてるよね？)
pc使えるようになったら確認して入れます

2021-05-16 09:51 UTC, ryoha000 requested changes
ボケっとレビューしてて申し訳ないんだけど実際に渡されたpropsを表示するようにして`dummyData`を消してほしいっていうissueだった:pray:

2021-05-16 09:53 UTC, ryoha000 requested changes

2021-05-16 09:53 UTC, ryoha000 commented on src/components/Results/Statistics.vue
> +        :rows="markdownTable.split('\n').length + 3"
この3を定数として宣言してほしい
意味が不明瞭なので

2021-05-16 09:53 UTC, ryoha000 commented on src/components/Results/Statistics.vue
> +    <Tab />
この中でも`tableForm `使うの違和感あるからpropsで渡すようにしてほしい

2021-05-16 09:53 UTC, ryoha000 commented on src/pages/Results.vue
> +      if (isNaN(Number(route.params.id))) return
これ(`Number(route.params.id)`)変数として宣言してほしい

2021-05-16 10:03 UTC, ryoha000 commented
traQで言った拡張機能のオプション、オンにしたらstatistics/responsesで怒られると思うので一緒に直しといてください:pray:

2021-06-25 11:13 UTC, ryoha000 commented
@Fogrexon どうですか？

2021-06-26 04:28 UTC, Fogrexon commented
@ryoha000 データ受け渡しはできたけどちょくちょくバグ残ってます
今日の夜に一通りのやつ出せるといいかなと思ってます

2021-06-26 16:13 UTC, Fogrexon commented on src/components/Results/Statistics.vue
> +        :rows="markdownTable.split('\n').length + 3"
これ元コードからそのままとってきたけど何の数字なんだ？

2021-06-26 16:33 UTC, Fogrexon commented
出しました
謎の+3については表示上の便宜を図るためだと勝手に推察しましたがいかかでしょうか
@ryoha000

2021-06-27 09:40 UTC, ryoha000 requested changes
結構エディタに怒られてる部分があると思うけどエラー、出てない？
エディタと同じことを指摘するのは馬鹿馬鹿しいから出てるなら直してからプッシュしてほしい(直し方が分からなかったらその旨を書いてほしい)
出てなかったら言って

あと使ってないから`dummyData`はファイルごと消しちゃってください

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Statistics/Data.vue
>  import Responces from './Responces.vue'
Responsesのタイポ

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Statistics/Data.vue
> +      required: true
```suggestion
      type: Array as PropType<ResponseResult[]>,
      default: []
```

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Statistics/Data.vue
> +      required: true
```suggestion
      type: Array as PropType<QuestionDetails[]>,
      default: []
```

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Statistics/Data.vue
> +      countedData: countData(props.questions, props.results),
こうやって書くんじゃなくて`computed`でちゃんと宣言してほしい
`props`が変わった時追従しない

あと`null`のときダメって`template`部分で怒られてませんか？
`null`を返すのはハンドリングがめんどくさいので空配列を返しましょう(下でも指摘します)

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Individual.vue
> +    ></pagination> -->
```suggestion
    個人の回答を表示する
```
これぐらいでいいです:+1:

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Individual.vue
>  // import Pagination from '/@/components/Utils/Pagination.vue'
消しちゃって 🙆‍♂️

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Individual.vue
>      // pagination: Pagination
消す

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Individual.vue
> +      required: true
```suggestion
      type: Array as PropType<ResponseResult[]>,
      default: []
```

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Individual.vue
> +      required: true
```suggestion
      type: Array as PropType<QuestionDetails[]>,
      default: []
```

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/ResultTab.vue
>      const selectedTab = ref('Statistics')
```suggestion
    const selectedTab = ref<DetailTabTypes>('statistics')
```
ほかのキャストしてるところも直す

これ下の`detailTabs.includes(selectedTab.value)`で赤線出てない？

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Spreadsheet.vue
> +import { TableFormStyle, tableFormTabs } from './use/utils'
これ`TableFormStyle`じゃなくて`TableFormTypes`じゃない？
エディタに怒られてない？

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Spreadsheet/ScrollView.vue
> +  TableFormStyle,
同じくこれ`TableFormStyle`じゃなくて`TableFormTypes`じゃない？
エディタに怒られてない？

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Spreadsheet/ScrollView.vue
> +    }
これの`index`、`any`って怒られてない？

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Spreadsheet/ScrollView.vue
> +      showColumns.value[index] = !showColumns[index]
```suggestion
      showColumns.value[index] = !showColumns.value[index]
```

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Spreadsheet/ScrollView.vue
>        isTextTable,
この`isTextTable`、関数ってエディタに怒られてない？
`get`かなんか接頭語につけたほうがいいかも

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Spreadsheet/Tab.vue
> +import { TableFormStyle } from '../use/utils'
これ`TableFormStyle`じゃなくて`TableFormTypes`じゃない？
エディタに怒られてない？

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Spreadsheet/Tab.vue
> +    },
ここ`v-model`で受け取るようにしたほうがよさそう
↑ではった`src\components\Explorer\DropdownMenu.vue`の`modelValue`と`update:modelValue`を見たらわかると思う

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Spreadsheet/Tab.vue
>      }
これはイベントにして`update:modelValue`で

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Spreadsheet/TableBody.vue
> +      required: true
```suggestion
      type: Array as PropType<ResponseResult[]>,
      default: []
```

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Spreadsheet/TableBody.vue
>    name: 'TableHeader',
```suggestion
  name: 'TableBody',
```

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Statistics.vue
> +  TableFormStyle,
これ`TableFormStyle`じゃなくて`TableFormTypes`じゃない？
エディタに怒られてない？

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Statistics.vue
> +      required: true
```suggestion
      type: Array as PropType<ResponseResult[]>,
     default: []
```

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Statistics.vue
> +      required: true
```suggestion
      type: Array as PropType<QuestionDetails[]>,
      default: []
```

2021-06-27 09:40 UTC, ryoha000 commented on src/components/Results/Statistics.vue
> +    </div>
`SpreadSheet`と同じなので、ここの部分を`<slot>`にして`props`で`table-form-tabs`を受け取るコンポーネントを新しく作って、`SpreadSheet`と`Statistics`で使うようにしましょう

2021-06-27 09:40 UTC, ryoha000 commented
途中で送っちゃった
まだレビューあります

2021-06-27 09:53 UTC, ryoha000 requested changes
`src\components\Results\Statistics\Responces.vue`の`template`部分で怒られてると思うのでそっちも修正しておいてください

2021-06-27 09:53 UTC, ryoha000 commented on src/components/Results/Statistics/Tab.vue
> +import { TableFormStyle } from '../use/utils'
これ`TableFormStyle`じゃなくて`TableFormTypes`じゃない？
エディタに怒られてない？

2021-06-27 09:53 UTC, ryoha000 commented on src/components/Results/Statistics/Tab.vue
>      <button v-if="canDownload" @click="downloadTable">
このボタンを入れられる`<slot>`を作って`SpreadSheet/Tab`と共通化してほしい
`SpreadSheet/Tab`のところで`v-model`云々って言ってると思うのでコンポーネントのインターフェースはそれに合わせてください

2021-06-27 09:53 UTC, ryoha000 commented on src/components/Results/use/utils.ts
> +export const textareaAdditionalLineNum = 3
```suggestion
export const TEXTAREA_ADDITIONAL_LINE_NUM = 3
```

2021-06-27 09:53 UTC, ryoha000 commented on src/components/Results/use/utils.ts
> +
ここから下の関数ってコピペしてきたやつですか？
自分で書いたならレビューするしそうじゃないならとりあえずはこれでいいです

2021-06-28 15:06 UTC, ryoha000 commented on src/components/Results/Spreadsheet/Tab.vue
> +    },
ごめんこれやっぱりやらないでいいです
`src/components/UI/Tab.vue`これを使うようにしてください

2021-06-28 15:06 UTC, ryoha000 commented on src/components/Results/Spreadsheet/Tab.vue
> +import { TableFormStyle } from '../use/utils'
`src/components/UI/Tab.vue`を使うようにしてほしいためclose

2021-06-28 15:07 UTC, ryoha000 commented on src/components/Results/Statistics/Tab.vue
> +import { TableFormStyle } from '../use/utils'
`src/components/UI/Tab.vue`を使うようにしてほしいためclose

2021-06-28 15:07 UTC, ryoha000 commented on src/components/Results/Statistics/Tab.vue
>      <button v-if="canDownload" @click="downloadTable">
`src/components/UI/Tab.vue`を使うようにしてほしいためclose

2021-06-28 15:07 UTC, ryoha000 commented on src/components/Results/ResultTab.vue
> +      required: true
`src/components/UI/Tab.vue`を使うようにしてほしいためclose

2021-06-28 15:07 UTC, ryoha000 commented on src/components/Results/ResultTab.vue
> +      required: true
`src/components/UI/Tab.vue`を使うようにしてほしいためclose

2021-06-28 15:15 UTC, ryoha000 commented on src/components/Results/Statistics/Data.vue
> +      countedData: countData(props.questions, props.results),
やっぱりこれは別PRでやるのでやらないでいいです
closeします

2021-06-28 16:12 UTC, ryoha000 approved these changes

2021-06-28 16:12 UTC, merged