タブのコンポーネント
traPtitech/anke-to-UI pull request #350
Opened 2021-05-15 05:50 UTC by kohbanye

Tabコンポーネントを作りました

2021-05-15 06:00 UTC, kohbanye commented
下線が動くアニメーションつけたんですけど、最初に下線つける場所を選択されてるタブの位置で初期化したら画像とかがあると(読み込みが遅いから？)↓みたいに変な位置になっちゃって困ってます
![スクリーンショット 2021-05-15 14 44 33](https://user-images.githubusercontent.com/66658420/118349737-7dc4d580-b58d-11eb-988c-6231e581ef3e.png)

2021-05-16 04:12 UTC, ryoha000 commented
pc使えるようになったら見ます

2021-05-16 08:01 UTC, kohbanye commented
多分解決できたとおもいます

2021-05-16 11:04 UTC, ryoha000 requested changes
めっちゃいい感じのアニメーションつけれてていいと思います
いったところだけちょっとなおしてもらえれば:pray:

2021-05-16 11:04 UTC, ryoha000 commented on src/components/UI/Tab.vue
> +  box-sizing: border-box;
今見たらほかの要素にはついてなかったんですね
index.scssの`#app`のなかに入れてこっちは消してください:pray:

2021-05-20 17:31 UTC, kohbanye commented
少し遅くなりましたが直しました

2021-05-21 12:18 UTC, ryoha000 approved these changes
いいと思います:LGTM::yosa::+1:

2021-05-21 12:19 UTC, merged