/questionnaires/:idページの組み立て #311
traPtitech/anke-to-UI pull request #423
Opened 2021-06-27 12:25 UTC by wakashi1

anke-toのresultのページにidページを作る。どのファイルにコンポネントを作るかはわかりませんでした。あとidページっていうのがどんなものなのかもわかりませんでした。

2021-06-27 13:16 UTC, ryoha000 commented
これはresultのページのことではないですね
issueに「/questionnaires/:idページ」って書いたのはそこのURLみたいなページを書くっていうことです
`:id`って書いたのはこういう記法を念頭に置いて書いています
https://router.vuejs.org/ja/guide/essentials/dynamic-matching.html
なので`id`ページではないです

今現在動いてるanke-toのどのページに当たるかはわかりましたか？
分かったら一例のURLを張ってみてほしいです

2021-07-06 13:59 UTC, wakashi1 commented
https://anke-to.trap.jp/questionnaires/925
こういうページをどうにかするってことですか？

2021-07-06 14:53 UTC, wakashi1 commented
src/componentsにquestionnairesのフォルダとsrc/pagesにQuestionnaires.vueを作って、フォルダにInformationとQuestionのタグのやつを作るかんじで実装しようと思っています。

2021-07-06 14:55 UTC, wakashi1 commented
組み立てっていうのはhttps://anke-to.trap.jp/questionnaires/925で今表示されてるのをコードにするってことですか？

2021-07-13 20:30 UTC, ryoha000 commented
ごめんなさい、返答し忘れてました？
もしそうならめっちゃ申し訳ないです。:pray:
遅いなと思ったら遠慮なくメンション飛ばしてください

> src/componentsにquestionnairesのフォルダとsrc/pagesにQuestionnaires.vueを作って、フォルダにInformationとQuestionのタグのやつを作るかんじで実装しようと思っています。

そうですね、そんな方針でいいと思います:+1:
ただ表示するアンケートは一見なので`questionnaires`ではなくて単数形でお願いします

> 組み立てっていうのは https://anke-to.trap.jp/questionnaires/925 で今表示されてるのをコードにするってことですか？

そうです
`Targeted`で使っているように`Card`コンポーネントを使ってください

2021-09-14 18:29 UTC, ryoha000 commented
@wakashi1 
これって組み立てはとりあえずひと段落ついた感じですかね？(まだ見てない)
レビューしてほしいタイミングになったら一声欲しいです:pray:

2021-09-20 06:50 UTC, wakashi1 commented
わかりました

2021-11-20 10:57 UTC, wakashi1 commented
レビューお願いします！

2021-11-23 14:44 UTC, ryoha000 requested changes
https://github.com/traPtitech/anke-to-UI/pull/423/files# をみたり`npm run type-check`をしたらわかると思うけどlintに怒られてるからそこも直してほしい

2021-11-23 14:44 UTC, ryoha000 commented on src/components/Questionnaire/Informations.vue
> +    return {}
👍

2021-11-23 14:44 UTC, ryoha000 commented on src/components/Questionnaire/Information/Manipulation.vue
> +      props.questionnaire.questionnaireID
```suggestion
    const questionnaireLink =
      `https://anke-to.trap.jp/responses/new/${props.questionnaire.questionnaireID}`
```
こっちの方がシンプル

2021-11-23 14:44 UTC, ryoha000 commented on src/components/Questionnaire/Information/Manipulation.vue
> +    }
```suggestion
    const LinkCopy = () => {
      navigator.clipboard.writeText(questionnaireLink)
    }
```
関数は基本的に↑みたいにarrow functionで書いてほしい

2021-11-23 14:44 UTC, ryoha000 commented on src/components/Questionnaire/Information/Manipulation.vue
> +    let linkcopy = false
```suggestion
    const linkcopy = ref(false)
```
って書いて変更時に
```
linkcopy.value = true
```
としないとリアクティブに値に追従してくれません(今回だと`linkcopy`の値が変わったことにvueが気づけなくて「リンクコピーされました」が表示されない)
リンクコピーされました

2021-11-23 14:44 UTC, ryoha000 commented on src/components/Questionnaire/Information/Manipulation.vue
> +      props.questionnaire.questionnaireID
ここも`ref`でくるんでください

2021-11-23 14:44 UTC, ryoha000 commented on src/components/Questionnaire/Information/Manipulation.vue
> +    }
mmmが関数名から何をする関数なのかがわからないので変えてほしいです

そもそもここ使ってない？

2021-11-23 14:44 UTC, ryoha000 commented on src/components/Questionnaire/Information/Myanswer.vue
> +            data.submitted_at
```suggestion
          <router-link :to="`/responses/${data.responseID}`">{{
            data.submitted_at
```

2021-11-23 14:44 UTC, ryoha000 commented on src/components/Questionnaire/Questions/Questions.vue
> +        </div>
```suggestion
          <ReadonlyRadio v-if="questioncontent.question_type == 'MultipleChoice'" :contents="questioncontent.options"></ReadonlyRadio>
          <ReadonlyTextarea v-if="questioncontent.question_type == 'TextArea'"></ReadonlyTextarea>
```
こういう風にネストせずに`v-if`してほしい

2021-11-23 14:44 UTC, ryoha000 commented on src/components/Questionnaire/Questions/Questions.vue
> +          <ReadonlyNumber></ReadonlyNumber>
[issueたてた](https://github.com/traPtitech/anke-to-UI/issues/691)けど今ある質問のコンポーネントに`readonly`属性を付ける予定だからそっちを使ってほしい

2022-01-11 12:50 UTC, wakashi1 commented
おそくなってすみません。直したんですが、readonlyのところは放置になってます。

2022-01-18 12:14 UTC, ryoha000 commented on src/components/Questionnaire/Information/Manipulation.vue
> +    const linkcopyboolean = ref(false)
`isLinkCopied`とかにしてほしいです

2022-01-18 12:14 UTC, ryoha000 commented on src/components/Questionnaire/Information/Manipulation.vue
> +    }
いくつか変えてほしいポイントがあります
- 関数名を頭小文字にしてほしい
- linkがコピーされたフラグ用の変数はこの関数の中で使えるんで受け取らないでください
  - 変更は`linkcopyboolean.value = true`でできます
- このフラグは一定時間で`false`になってほしいのでsetTimeoutを使って1秒くらいで`false`になるようにしてほしいです
  - https://developer.mozilla.org/ja/docs/Web/API/setTimeout

2022-01-18 12:14 UTC, ryoha000 commented on src/components/Questionnaire/QuestionnaireHeader.vue
> +    :tabs="detailTabsQuestionnaire"
`src\components\Results\Spreadsheet.vue`を参考に`v-model`とかを使ってください

2022-01-25 06:39 UTC, wakashi1 commented
直しました。readonlyのところもUIにあるやつ使うようにしました。

2022-03-08 11:47 UTC, ryoha000 reviewed
めちゃくちゃ遅くなっちゃってすみません:pray:
cssは後でつける感じでコメント直してくれたら入れちゃいましょう

2022-03-08 11:47 UTC, ryoha000 commented on src/components/Questionnaire/Information/Myanswer.vue
> +          ><span>ゴミ箱</span>
iconにしてほしい
`mdi.ts`に https://materialdesignicons.com/ ここのアイコン名を追加する

2022-03-08 11:47 UTC, ryoha000 commented on src/components/Questionnaire/Informations.vue
> +    <Summary :questionnaire="questionnaire"></Summary>
```suggestion
    <Summary :questionnaire="questionnaire" />
```
こういう風にしてほしい

2022-03-08 11:47 UTC, ryoha000 commented on src/components/Questionnaire/Informations.vue
> +    myresponses: {
```suggestion
    myResponses: {
```
ほかのところも

2022-03-08 11:47 UTC, ryoha000 commented on src/components/Questionnaire/Questions/Is_required.vue
> +<template>
ファイル名は`IsRequired.vue`にしてほしい

2022-03-08 11:47 UTC, ryoha000 commented on src/components/Questionnaire/Information/Myanswer.vue
> +  name: 'Myanswer',
```suggestion
  name: 'MyAnswer',
```
ファイル名も

2022-03-08 14:51 UTC, ryoha000 approved these changes
:LGTM:

2022-03-08 14:51 UTC, merged