質問のコンポーネントの実装 #310
traPtitech/anke-to-UI pull request #451
Opened 2021-07-12 11:03 UTC by kohbanye

#310 
実装しました

`box-sizing: border-box;`が効いてない気がしてところどころで指定してます
(`index.scss`のborder-boxが効いてない？)

2021-07-12 19:43 UTC, ryoha000 requested changes
全体的にいい感じです:+1:
ちょっと修正お願いします

2021-07-12 19:43 UTC, ryoha000 commented on src/components/UI/LinearScale.vue
> +    let selectedIndex = ref() as Ref<number>
これはそもそも`modelValue`を用いて`computed`で値を作ってほしいです

2021-07-12 19:43 UTC, ryoha000 commented on src/components/UI/LinearScale.vue
> +      context.emit('update:modelValue', props.range[index])
`computed`にしてほしいっていったのはここで二重管理みたいになるのを防ぐためです

2021-07-12 19:43 UTC, ryoha000 commented on src/components/UI/QuestionCheckbox.vue
> +      }
ここは`checkedContents`をこの関数内でしか使わないようにして、`modelValue`をつかって一々updateする配列を作ったほうがいと思います

2021-07-12 19:43 UTC, ryoha000 commented on src/components/UI/QuestionInput.vue
> +    placeholder="回答"
ちょっと文字サイズを1remぐらいにしてほしいです

2021-07-12 19:43 UTC, ryoha000 commented on src/components/UI/QuestionInputNumber.vue
> +<template>
このコンポーネント、`QuestionInput`をまとめたいですね
typeを受け取るようにしてほしいです

2021-07-12 19:43 UTC, ryoha000 commented on src/components/UI/QuestionRadio.vue
> +    let selectedIndex = ref() as Ref<number>
上で言ったやつと同じ

2021-07-12 19:43 UTC, ryoha000 commented on src/components/UI/QuestionTextarea.vue
> +  margin: -5px 0;
このmargnってどういう意図でした？
僕の手元で少し試した感じだと変わらなそう？

`input`のほうと`underline`は共通化していい気がしています

2021-07-12 19:43 UTC, ryoha000 commented on src/components/UI/QuestionTextarea.vue
> +  <textarea
ちょっと文字間欲しいです

2021-07-12 19:43 UTC, ryoha000 commented on src/components/UI/QuestionCheckbox.vue
> +    <label
これに`cursor: pointer;`つけてhover時のopacityかけてほしいです

2021-07-12 19:43 UTC, ryoha000 commented on src/components/UI/QuestionRadio.vue
> +    <label
これに`cursor: pointer;`つけてhover時のopacityかけてほしいです

2021-07-19 17:44 UTC, kohbanye commented on src/components/UI/QuestionTextarea.vue
> +  margin: -5px 0;
<img width="266" alt="スクリーンショット 2021-07-20 2 26 11" src="https://user-images.githubusercontent.com/66658420/126203437-8f3486c1-0bc0-491d-977d-8b6d4a72f566.png">
こんな感じにずれちゃいませんか？

2021-07-20 01:27 UTC, ryoha000 commented on src/components/UI/QuestionTextarea.vue
> +  margin: -5px 0;
あ～確かに
これってpaddingの値と同じである必要がある感じですかね？
それなら(scssの)変数として切り出してそれを当ててほしいです
あとpx数を指定するときはできるだけ16の倍数にして微調整したいときだけ8px, 4px, 2px, 1pxを使うようにしてほしいです
こんな感じ？
```
$textarea-border: 1px;
$textarea-padding: 4px;
$underline-margin: calc(-1 * (#{$textarea-border} + #{$textarea-padding}));
```

`input`のほうと共通化するときは`margin`だけコンポーネントのclassとして外につけてください

2021-07-20 07:38 UTC, kohbanye commented
直しました

2021-07-20 22:25 UTC, ryoha000 approved these changes

2021-07-20 22:25 UTC, ryoha000 commented on src/components/UI/InputUnderline.vue
> +  margin-top: -1px;
コンポーネントの中で`margin-top: -1;`するのは微妙な気がします
このコンポーネントの責務は「focusが当たった時出てくる下線の実装」なのでそれと関係ない`margin`の値はあるべきではないと思います
なのでこのコンポーネントを使う側が`margin`をあてるよう実装してほしいです

2021-07-20 22:25 UTC, ryoha000 commented on src/components/UI/QuestionInput.vue
>      transform: scaleX(1);
↑のコメントと同様に責務を考えるとこれは下線のコンポーネント内でやるべきことだと思います
ただ、クラスで指定できないのでどうやるかですが、
`focus`された、タグ名が`input`か`textarea`な要素の弟なら～みたいな感じでかなと思います(いい実装が思いつかなかった)

2021-07-20 22:25 UTC, ryoha000 commented on src/components/UI/QuestionInput.vue
> +  <input-underline :class="$style.underline" />
呼び出し元でborderの幅のmarginをつけるようにしてください

2021-07-20 22:25 UTC, ryoha000 commented on src/components/UI/QuestionTextarea.vue
>  .textarea {
折角変数に切り出したので`padding`の値と`border`の値でそれぞれを指定してほしいです

2021-07-20 22:25 UTC, ryoha000 commented on src/components/UI/QuestionTextarea.vue
> +  margin-top: #{$underline-margin};
`calc`のなかとかじゃなければ`$underline-margin`だけで変数は指定できます

2021-07-20 22:26 UTC, ryoha000 requested changes
間違ってapproveしてしまった

2021-07-21 16:20 UTC, kohbanye commented
直しました

2021-07-21 19:58 UTC, ryoha000 approved these changes

2021-07-21 19:58 UTC, ryoha000 commented on src/components/UI/InputUnderline.vue
> +.focused {
js側で渡すんじゃなくて
```
.underline {
  ...
  textarea:focus + &,
  input:focus + & {
    transform: scaleX(1);
  }
}
```
みたいなイメージでした

ちょっと読みづらい気もしますがjsは処理がちょっと複雑になるので

2021-07-21 19:58 UTC, ryoha000 commented on src/components/UI/QuestionTextarea.vue
> +$underline-margin: calc(-1 * (#{$textarea-border} + #{$textarea-padding}));
`input`の方みたいに`calc`じゃなくて直接計算できるの知らなかった...
直接計算するようにしてください:pray:

2021-07-21 19:59 UTC, ryoha000 requested changes
また間違えた

2021-07-25 04:50 UTC, kohbanye commented
直しました

2021-07-29 17:01 UTC, kohbanye commented
@ryoha000

2021-07-30 03:53 UTC, ryoha000 approved these changes
忘れてた、ごめんなさい:pray:
LGTM

2021-07-30 03:53 UTC, merged