右上のアイコンを自分のものにする #332
traPtitech/anke-to-UI pull request #468
Opened 2021-07-22 08:42 UTC by annin3

booQの実装参考にしてみたのですが上手く行きませんでした

- src/store/index.ts の28行目
- src/components/Navigation/Header.vue の43行目
でエラーが出ているのですが原因がわかりませんでした

- src/store/index.ts の追加した部分
- src/use/me.ts
で何をやってるのかあんまり理解できてません・・・
よろしくお願いします

2021-07-22 09:05 UTC, ryoha000 commented
エラーの文面からどういう問題が発生しているのか見当はついていますか？

src/store/index.ts の追加した部分、src/use/me.ts のわからないところって具体的にどこですか？

2021-07-22 09:53 UTC, annin3 commented
>エラーの文面からどういう問題が発生しているのか

src/store/index.ts の方は型不一致によるものだと認識してます
User→Meにしたら消えますが src/use/me.ts の方で新しくエラーが出てしまいます
src/components/Navigation/Header.vue の43行目のほうはよくわかりません・・・

>src/store/index.ts の追加した部分、src/use/me.ts のわからないところ

正直何がわからないのかわからない状態ではあるのですが・・・
- src/store/index.ts のほうはfetchMe()内のcommitやrootActionContext()がどういう働きをしてるのかがいまいちわかってない
- src/use/me.tsのほうは9行目が何をしてるのかがわかってない
- 
気がしてます

2021-07-22 14:18 UTC, ryoha000 commented
`Property 'getMe' does not exist on type 'Apis'.`というエラーが出てます
まぁこれは見ればわかると思うんですが`Apis`という型に`getMe`はないと怒られてます
このAPIの定義まわりは自動生成で作ってるのでbooQの方とは微妙に関数名だったり型名が違います(そもそも同じレスポンスが返ってくるわけではない)
なので`apis.`で適当な補完先を見つけてそれを使うようにしてください
今回の場合は`apis.getUserMe`です
あとは`apis.getUserMe`の返り値の型に合わせてください

commitとかについては下のリンクを読んでみてください
https://vuex.vuejs.org/ja/guide/
`rootActionContext`は`commit`を得るためのおまじないだと思ってくれて大丈夫です

me.tsの9行目に関してはstoreにおいてあるmeというstateをcomputedでくるんでリアクティブにしています
最後のびっくりはnon-null assertion operatorというものです

2021-07-23 06:53 UTC, annin3 commented
getMeではエラー出てません・・・
現状出ているのは
src/store/index.ts の28行目の
`Argument of type 'Me' is not assignable to parameter of type 'User'.
  Type 'Me' is missing the following properties from type 'User': userId, displayName, iconFileId, twitterIdts(2345)`
と
src/components/Navigation/Header.vue の43行目の
`Property 'name' does not exist on type 'ToRefs<User>'.Vetur(2339)`
の2つです
あと`apis.getUserMe`が見当たらないです・・・
![image](https://user-images.githubusercontent.com/63178126/126747031-1075fd9c-8255-49c4-af2c-293138aa6854.png)

2021-07-23 07:24 UTC, ryoha000 commented
あ～多分swaggerが書き換わったのを反映していないんだと思います
`npm run gen-api`し直してみてください

2021-07-23 08:50 UTC, annin3 commented
`npm run gen-api`でいい感じになりました:pray:

ただsrc/components/Navigation/Header.vue の43行目のほうのエラーが直せませんでした
`Property 'name' does not exist on type 'ToRefs<Me>'.Vetur(2339)`
ToRefsがよくわかってないです・・・

2021-07-23 10:33 UTC, ryoha000 commented
toRefsに関してはこのあたりを見ればわかるかもしれません
https://qiita.com/ryo2132/items/6dc51ede8082dea75812#torefs

エラーについては「`ToRefs<Me>`という型には`name`というプロパティはない」というものですね

2021-07-23 12:44 UTC, annin3 commented
↑のエラーについては解決しました、ありがとうございます
`myName`がundefinedになってしまってるのですがどうしてでしょうか。。。

2021-07-24 03:09 UTC, ryoha000 commented
どこで値がセットされてると思いますか？
↑ではったvuexのguideとかを見ると分かると思います

2021-09-07 14:45 UTC, annin3 commented
修正しました

2021-09-07 16:33 UTC, ryoha000 requested changes

2021-09-07 16:33 UTC, ryoha000 commented on src/App.vue
> +  <div v-if="isFetched" :class="$style.container">
スタイルはつけなくていいんで v-else で読み込み中みたいなの出しといてほしいです

2021-09-07 16:33 UTC, ryoha000 commented on src/store/index.ts
> +    count: 0,
count はただの例だったんで消しちゃってくれて大丈夫です

2021-09-08 03:29 UTC, ryoha000 commented on src/App.vue
> +  <div v-if="isFetched" :class="$style.container">
兼ねてません
あとで差し替えるための一時的なもので大丈夫です

2021-09-08 23:07 UTC, ryoha000 approved these changes
LGTM！

次のissueだけどloadingぐらいしか気軽に取れるものがない:pray:

2021-09-08 23:07 UTC, merged