develop-Administrates
traPtitech/anke-to-UI pull request #631
Opened 2021-10-19 12:21 UTC by tantakaa

2021-11-23 12:17 UTC, ryoha000 commented
cardコンポーネントの修正がすでにmasterに入ったからrebaseしてほかで使ってるみたいにcardコンポーネントを使ってほしい

2021-12-22 14:23 UTC, ryoha000 requested changes
これだけ直してもらったらOK:+1:

2021-12-22 14:23 UTC, ryoha000 commented on src/components/UI/SwitchIcon.vue
> +    },
`status`が`true`なときが何なのかよくわかんないから`isResponded`とかにしてほしい(これが何のアイコンだったかうろ覚えだからもっといいやつがあったらそれで)

2022-01-18 09:50 UTC, ryoha000 requested changes

2022-01-18 09:50 UTC, ryoha000 commented on src/components/UI/LinkIconQuestion.vue
> +    <switch-icon :status="status" :size="iconsize" />
ここも名前変えてほしい

2022-01-18 09:50 UTC, ryoha000 commented on src/components/UI/LinkIconQuestion.vue
> +      required: true
こっちも

2022-01-18 13:55 UTC, ryoha000 reviewed
口頭で言ったけど

2022-01-18 13:55 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
> +        <div :class="$style.res_time_limit">
`resTimeLimit`にしてほしい

2022-01-18 13:55 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
> +        <div :class="$style.modified_at">
こっちも

2022-01-19 07:25 UTC, ryoha000 commented
口頭で言ったけどwidthを直接指定するんじゃなくてgridかなんかでcontainerのwidthに対して半分半分に分け合うようにしてほしい

2022-02-23 12:11 UTC, tantakaa commented
上の修正で問題なさそうだったらマージしても大丈夫ですか？

2022-03-06 03:20 UTC, annin3 reviewed
2箇所だけコメントしました。

2022-03-06 03:20 UTC, annin3 commented on src/components/UI/SwitchIcon.vue
> +.icon {
このスタイル必要なさそう

2022-03-08 12:49 UTC, ryoha000 approved these changes
mergeしちゃいます:+1:

2022-03-08 12:49 UTC, merged