targetedページのcssの調整
traPtitech/anke-to-UI pull request #65
Opened 2020-10-14 11:10 UTC by annin3

レイアウトを現在のanke-toにあわせました。

2020-10-14 20:16 UTC, ryoha000 requested changes

2020-10-14 20:16 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
>      text-align: left;
flexにしたらいらなくなります

2020-10-14 20:16 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
>      min-width: 10em;
意図がつかめませんでした

2020-10-14 20:16 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
>      font-size: 15pt;
font-sizeはremを単位にして指定してください
何でもいいですが揃えたいので

2020-10-14 20:16 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
> +    padding-top: 0.8em;
ここもmarginで

2020-10-14 20:16 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
>      padding-bottom: 0.8em;
ここもmarginで

2020-10-14 20:16 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
>      min-width: 8em;
意図がつかめませんでした

2020-10-14 20:16 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
>      text-align: left;
containerにこれを付けたらいらなくなります

2020-10-14 20:16 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
> +    text-align: left;
containerにこれを付けたらいらなくなります

2020-10-14 20:16 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
> +    min-width: 5em;
意図がつかめませんでした

2020-10-14 20:16 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
>    .tableItemDate {
`inline-block`で横に並べるのは可読性が低く調整しづらいので
```
display: flex;
align-items: center;
```
で並べてください

2020-10-14 20:16 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
> +.columnLimit {
`columnModified`とclassを統合しちゃってください
2つ目の要素の`margin-right`は`last-of-type`で消してくれてもいいですし、別に消さないでもいいです

2020-10-14 20:16 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
>    .tableItemDate {
`padding-left`で`columnLimit `のmargin-leftがいらないように調整してください

2020-10-14 20:16 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
> +  border-bottom: solid 1.5px #d9d9d9;
本家とは変わりますが流石に気持ち悪いので最後の要素のborderは隠すようにしてください

2020-10-14 20:16 UTC, ryoha000 commented on src/pages/Targeted.vue
> +.test {
class名そのままにしてませんか？

2020-10-16 04:06 UTC, annin3 commented
修正しました。
確認お願いします。

2020-10-18 00:34 UTC, ryoha000 requested changes

2020-10-18 00:34 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
>      <div>
ここのdivに`$style.tableItemDate`と`$style.column`のstyleを当ててください

2020-10-18 00:34 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
> +          <p>更新日: {{ questionnaire.modified_at }}</p>
ここのpタグ(別に親でもいいです)にfont-weightつけてください

2020-10-18 00:34 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
>      <div>
上のDescriptionと間が空きすぎなのでmarginを調整するなり、pタグをdivに置き換えるなりして近づけてください(アンケート名と説明の間より空いているので規則性がない)
pタグには段落の構造的意味がありますがここは別に段落というわけでもないのでdivの方が扱いやすいと思います。(cssのサニタイズとかをしてないのでpタグだと勝手にmarginがついてめんどくさい)

2020-10-18 00:34 UTC, ryoha000 commented on src/pages/Targeted.vue
> +      <div :class="$style.frame">
ここにpaddingをつけるならCardContentDetailのcontainerのpaddingは要らないと思います

2020-10-18 00:34 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
> +.tableItemTitle {
この中にあるアイコンとアンケート名の間を気持ち開けてください(変更してないところにコメントを付けられないのでここに書きます)
あとアイコンのところのclass使ってないので消してください

2020-10-18 00:34 UTC, ryoha000 commented
遅くなってすみません:pray:

2020-10-18 07:32 UTC, annin3 commented on src/pages/Targeted.vue
> +      <div :class="$style.frame">
旧anke-toのレイアウトに近づけるためにそれぞれにpaddingを入れたのですが、片方のみにして調整し直したほうが良いでしょうか？
|  現在のコード |  Targetedのみpadding | CardContentDetailのcontainerのみpadding |
| ---- | ---- | ---- |
|  ![image](https://user-images.githubusercontent.com/63178126/96361213-da2e5680-115e-11eb-9c57-08636091328f.png)| ![image](https://user-images.githubusercontent.com/63178126/96361226-ed412680-115e-11eb-9723-cfef6d7375b5.png)|![image](https://user-images.githubusercontent.com/63178126/96361268-34c7b280-115f-11eb-9b08-6e677c8359ac.png)|
||boderlineの上下の隙間がなくなる|boderlineの左右の隙間がなくなってしまう|

2020-10-18 07:33 UTC, annin3 commented on src/components/UI/CardContentDetail.vue
> +.tableItemTitle {
すみません、display: flex;を使った上で子要素間に隙間を開ける方法がわかりませんでした。

2020-10-18 13:31 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
> +.tableItemTitle {
単純に子要素にmargin-rightなりmargin-leftなりつければ大丈夫です

2020-10-18 13:40 UTC, ryoha000 commented on src/pages/Targeted.vue
> +      <div :class="$style.frame">
あ～いい感じの比較ありがとう
「Targetedのみpadding」の状態から、CardContentDetailのcontainerの上と下にpaddingつけて、最初の上と最後の下だけpadding外すようにしてみてください
この辺は僕が適当に「こっちの方がいいんじゃない？」って言ってるだけなので、違う方がいいと思ったら遠慮なくいってください

2020-10-18 13:40 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
> +.tableItemTitle {
大体8pxくらいを想定してます

2020-10-19 03:16 UTC, annin3 commented
修正しました、確認お願いします

2020-10-19 03:38 UTC, ryoha000 requested changes

2020-10-19 03:38 UTC, ryoha000 commented on src/pages/Targeted.vue
> +  padding: 2rem;
```suggestion
  padding: 1rem 1.5rem;
```
こっちの方が見栄え良い気がするのでこのへんわちゃわちゃして申し訳ないんですがこれでお願いします:pray:

2020-10-19 03:38 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
>      <div :class="$style.tableItemTitle">
ちょっとこのファイル長いのでこのdivのところ、`router-link`の`to`と表示している文字を受け取るコンポーネントに切り出してください。

2020-10-19 08:43 UTC, annin3 commented
CardTitleに分けました
確認お願いします

2020-10-19 23:51 UTC, ryoha000 approved these changes

2020-10-19 23:51 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
> +    ></CardTitle>
ごめん、ここのコンポーネントを選んだ理由をちゃんと言ってなかった。あと渡さなきゃいけないプロパティまだあったわ:pray:
ここを切り出してほしいって言った理由はこのファイルが長いって言うのももちろんあるんだけど、再利用性が高いと思ったから。
アイコンと`router-link`を並べたい場所は多分他にもいくつかあって、そこにこの切り出したコンポーネントを使わせたかった。
だから名前は`CardTitle`とかじゃなくて`LinkIconText`とか？(微妙な気がするから変えてくれて全然いい)にしてほしい。
まだあったっていうのは、`size`を渡さなきゃいけなかったっていうことです
言葉足らず&想定不足で申し訳ない:pray:

2020-10-19 23:52 UTC, ryoha000 commented
ごめん、間違ってapproveしちゃった
まぁ上直せばマージなので

2020-10-20 01:51 UTC, annin3 commented on src/components/UI/CardContentDetail.vue
> +    ></CardTitle>
sizeというのはフォントのサイズのことで大丈夫ですかね？

2020-10-20 02:28 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
> +    ></CardTitle>
それとiconのサイズですね

2020-10-20 14:56 UTC, annin3 commented
すみません、直前のcommitのようにフォントサイズを調整しようとしたのですがうまくいきません。。。(iconはできました)
どこが間違ってるか教えていただけるとありがたいです

2020-10-20 17:41 UTC, ryoha000 commented
まずiconのsizeが指定できているのは`components/UI/Icon.vue`で`size`というプロパティを受け取って`svg`タグの`width`と`height`というAttributeにセットしています。
前に`:`がついているのはvue特有の記法で`v-bind:`の省略記法です。
`v-bind`のおかげで変数を変えたときに一々Attributeをセットしなおさなくても、変数の変更に追従してセットしなおします。
Attributeを指定しているんじゃなくて`style`を指定していると勘違いしてしまったんだと思います。
なのでちゃんと`style`で指定してあげたらいいです。
その方法は`setup`のなかで`const fontSize = computed(() => `font-size: ${size}px;`)`みたいに定義してあげて、テキスト部分のタグの`style`というAttributeにセットしてあげたらいいです。
Attributeについてはここ( https://developer.mozilla.org/ja/docs/Web/HTML/Attributes )にたぶん一覧があります。(覚える必要は全くないです)

2020-10-21 12:16 UTC, annin3 commented
何度もすみません、まだうまく行かないのでもう一度見ていただけるとありがたいです

>Attributeを指定しているんじゃなくてstyleを指定していると勘違い

そのとおりでした

- styleのところは直前のcommitのような感じの理解であってますか？
- setupのところでいろいろエラーが出てしまっているのですが原因と対処法がわかりませんでした

2020-10-21 15:06 UTC, ryoha000 requested changes

2020-10-21 15:06 UTC, ryoha000 commented on src/components/UI/LinkIconQuestion.vue
> +    )
ここ俺のMDに書いたのが適当だったのが悪いんだけどいくつか書き方があって、
```
const fontSize = computed(() => `font-size: ${props.textsize}rem;`)
```
か
```
const fontSize = computed(() => ({ 'font-size': `${props.textsize}rem` }))
```
みたいにかける。
一つ目は単純にstringとして、二つ目はオブジェクトとしてstyleを書いてる感じ。
オブジェクトのキーに`-`を入れたいときはシングルクォート(`'`)でキーを囲むとできる。

2020-10-21 15:06 UTC, ryoha000 commented on src/components/UI/LinkIconQuestion.vue
> +      font-size: ${textsize}rem;
`1rem`が一般的な大きさだから`24rem`とかになると爆発しちゃう
もらってくる単位は`px`でも`rem`でもいいんだけど、どっちかというと`px`単位でpropsをもらった方がいいかな

2020-10-21 15:06 UTC, ryoha000 commented on src/components/UI/LinkIconQuestion.vue
> +  setup() {
`setup(props) {`

2020-10-21 15:06 UTC, ryoha000 commented on src/components/UI/LinkIconQuestion.vue
>  export default {
ここ`defineComponent`で書かないとvue側でうまく扱えない

2020-10-22 00:46 UTC, annin3 commented
ありがとうございます！できました！！ので確認お願いします
タイトル部分のフォントの大きさですが、現在のanke-toは20pxなんですがもう少し大きいほうがいいかなと思い24pxにしました
それに合わせてIconの大きさも大きくしました
不都合あれば戻します

2020-10-22 02:51 UTC, ryoha000 requested changes

2020-10-22 02:51 UTC, ryoha000 commented on src/components/UI/Card.vue
>    font-size: 15pt;
```suggestion
  font-size: 1.25rem;
```
見落としてた単位はpxかremで統一してほしい

2020-10-22 02:51 UTC, ryoha000 commented on src/components/UI/LinkIconQuestion.vue
> +  margin-bottom: 0.8em;
こことか他にも`em`が結構ありますがこれからは`rem`にしてほしいです
あとで一括置換するので今は直さなくて大丈夫です:pray:
めっちゃ適当にしか見れてなくてごめんなさい:pray:

2020-10-22 02:51 UTC, ryoha000 commented on src/components/UI/CardContentDetail.vue
> +      :textsize="24"
ちょっとでかいかな？
折角なのに悪いけど20にしてほしい:pray:

2020-10-22 04:17 UTC, annin3 commented
あとで置換するという部分以外は修正しました
確認お願いします

2020-10-22 08:47 UTC, ryoha000 approved these changes
:yosa:
LGTM

2020-10-22 08:47 UTC, merged