ヘッダー&サイドバーのstyle付け
traPtitech/anke-to-UI pull request #73
Opened 2020-10-20 08:56 UTC by kohbanye

style付けました
ロゴは旧anke-toから拝借してsrc/assetsに入れました

2020-10-20 19:09 UTC, ryoha000 requested changes

2020-10-20 19:09 UTC, ryoha000 commented on src/components/Navigation/SideBar.vue
> +    <router-link :class="$style.link" to="/targeted">Targeted</router-link>
このhoverしたら下線が伸びるコンポーネントは再利用できそうだから切り出してほしい

2020-10-20 19:09 UTC, ryoha000 commented on src/components/Navigation/Header.vue
> +      <img :class="$style.logo" src="/@/assets/anke-to_logo.png" />
若干拡大されて荒く見えるから元と同じ大きさにしてほしい
もとは
```
max-height: 1.75rem;
```
だった

2020-10-20 19:09 UTC, ryoha000 commented on src/components/Navigation/Header.vue
> +  margin: 0.4rem 2rem 0 0.5rem;
たぶん中央に見えなかったからこのmargin-topつけたんだと思うけど、上のaタグに`heght: 24px`つけたら中央に見えると思うからmargin-leftだけ指定する感じにしてほしい

2020-10-20 19:09 UTC, ryoha000 commented on src/components/Navigation/Header.vue
>      <route />
一番右端にUserIconが欲しいからそれようのコンポーネントを作ってほしい
ユーザーアイコンは`https://q.trap.jp/api/v3/public/icon/ユーザーID`でとれる

2020-10-21 16:18 UTC, kohbanye commented
修正しました

2020-10-21 18:20 UTC, ryoha000 requested changes

2020-10-21 18:20 UTC, ryoha000 commented on src/components/Navigation/SideBarLink.vue
> +    bottom: 3.5px;
```suggestion
    bottom: 4px;
```
8の倍数にしたいので

2020-10-21 18:20 UTC, ryoha000 commented on src/components/Navigation/SideBarLink.vue
> +  display: table;
`display: table`は扱いづらいのと別にtableなわけでもないから呼び出し元のコンポーネントで、その親のタグに
```
display: flex;
flex-direction: column;
```
とか付けた方がいい

2020-10-21 18:20 UTC, ryoha000 commented on src/components/Navigation/SideBarLink.vue
> +    width: 95%;
```suggestion
    width: calc(100% - 0.2rem * 2);
```
ここで95みたいなマジックナンバー使うより理由がありそうな形をしてた方がいい

2020-10-22 15:04 UTC, kohbanye commented on src/components/Navigation/SideBarLink.vue
> +  display: table;
`display: flex;`にしたら下線が伸びるやつの線がTargetedとかの文字をはみ出して横に伸びちゃうなーと思って`display: table;`にしてました

2020-10-22 18:40 UTC, ryoha000 commented on src/components/Navigation/SideBarLink.vue
> +  display: table;
それなら新しく`div`タグで<router-link>を囲えばいけると思う

2020-10-23 00:26 UTC, kohbanye commented
直しました

2020-10-23 17:39 UTC, ryoha000 requested changes

2020-10-23 17:39 UTC, ryoha000 commented on src/components/Navigation/SideBar.vue
> +  margin: 0.5rem 0;
ここは`padding`かな

2020-10-24 02:13 UTC, kohbanye commented
直しました

2020-10-24 02:28 UTC, ryoha000 commented
良さそう～～
masterに追従してくれたらマージします

2020-10-24 14:12 UTC, kohbanye commented
リベースしましたー

2020-10-25 00:58 UTC, ryoha000 approved these changes
:yoda:
LGTM

2020-10-25 00:58 UTC, merged